# Section 1 Questions 401-600: SOA & Managed Services, Client & GUI, Memory
# Format: (topic, subtopic, question, optA, optB, optC, optD, answer)

def get_questions():
    return [
# ── SOA & MANAGED SERVICES ── Service-Oriented Architecture ──
("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "SOA stands for:",
 "Service-Oriented Architecture","System-Only Access","Secure Online Application","Standard Operating Algorithm","A"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "In SOA, applications are built as a collection of:",
 "Monolithic blocks","Loosely coupled services","Hardware components","Physical modules","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "SOA enables different services to communicate through:",
 "Physical cables only","Standardized protocols and interfaces","Paper messages","Voice commands only","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "A key principle of SOA is:",
 "Tight coupling between components","Loose coupling and reusability of services","No communication between services","Only one service allowed","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "SOA allows organizations to:",
 "Only use one software application forever",
 "Integrate and reuse existing services across different applications",
 "Avoid using any technology",
 "Replace all software with hardware","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "Web services in SOA typically communicate using:",
 "Smoke signals","XML-based protocols like SOAP or REST","Morse code","Physical mail","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "SOAP in SOA stands for:",
 "Simple Object Access Protocol","Secure Online Application Platform","Standard Operating Access Point","System-Oriented Architecture Protocol","A"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "REST in the context of web services stands for:",
 "Really Easy Software Tool","Representational State Transfer","Remote Execution Standard Technique","Rapid Enterprise Service Technology","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "SOA promotes:",
 "Code duplication across all systems",
 "Service reusability across multiple applications",
 "One-time-use software",
 "Hardware-only solutions","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "An enterprise service bus (ESB) in SOA is used to:",
 "Transport physical goods",
 "Facilitate communication between different services",
 "Drive data entry forms",
 "Only send emails","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "Which of the following is a benefit of SOA?",
 "Increased dependency between systems",
 "Improved flexibility and interoperability",
 "More monolithic architectures",
 "Less code reuse","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "SOA is the predecessor concept to modern:",
 "Typewriter technology","Microservices architecture","Manual accounting","Physical filing","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "Service discovery in SOA allows applications to:",
 "Find and connect to available services dynamically",
 "Only use hardcoded connections",
 "Avoid all network communication",
 "Discover physical hardware locations","A"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "WSDL in SOA stands for:",
 "Web Services Description Language","Wide System Data Link","Wireless Service Delivery Layer","Web Standard Data Library","A"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "SOA helps legacy systems by:",
 "Replacing them entirely",
 "Wrapping them as services that can communicate with newer systems",
 "Deleting all old data",
 "Ignoring them completely","B"),

# ── Managed IT Services ──
("SOA & Managed Services","Managed IT Services",
 "Managed IT services means:",
 "A company manages all IT internally with no help",
 "A third-party provider manages and maintains IT systems on behalf of a client",
 "IT services that are free forever",
 "No IT services at all","B"),

("SOA & Managed Services","Managed IT Services",
 "A Managed Service Provider (MSP) typically handles:",
 "Only physical security guards",
 "IT infrastructure, security, monitoring, and support for clients",
 "Only catering services",
 "Only marketing","B"),

("SOA & Managed Services","Managed IT Services",
 "Which of the following is a managed service?",
 "A company fixing its own printers internally",
 "Outsourced 24/7 network monitoring by a third party",
 "An employee personally managing their laptop",
 "Using a personal calculator","B"),

("SOA & Managed Services","Managed IT Services",
 "Managed services help organizations:",
 "Increase internal IT workload",
 "Focus on core business while experts handle IT operations",
 "Avoid all technology entirely",
 "Hire more hardware technicians locally","B"),

("SOA & Managed Services","Managed IT Services",
 "SLA in managed services stands for:",
 "Service Level Agreement","Standard Local Access","System Linked Authorization","Software License Activation","A"),

("SOA & Managed Services","Managed IT Services",
 "An SLA in managed services defines:",
 "The color of the servers",
 "The expected performance, uptime, and responsibilities between provider and client",
 "The physical location of all employees",
 "The brand of coffee in the office","B"),

("SOA & Managed Services","Managed IT Services",
 "Proactive monitoring in managed IT services means:",
 "Waiting for problems to occur before fixing them",
 "Continuously monitoring systems to detect and resolve issues before they escalate",
 "Only checking systems once a year",
 "No monitoring at all","B"),

("SOA & Managed Services","Managed IT Services",
 "Which is an example of a managed cloud service?",
 "AWS Managed Database Service (RDS)",
 "A personal spreadsheet on your laptop",
 "A handwritten ledger",
 "A local calculator","A"),

("SOA & Managed Services","Managed IT Services",
 "Managed security services include:",
 "No security measures",
 "Firewall management, intrusion detection, and threat monitoring",
 "Only physical door locks",
 "Only CCTV cameras","B"),

("SOA & Managed Services","Managed IT Services",
 "A benefit of managed IT services is:",
 "Higher overall costs always",
 "Access to specialized expertise without hiring full-time staff",
 "Less reliable systems",
 "More work for internal teams","B"),

# ── Client-Server Model ──
("SOA & Managed Services","Client-Server Model",
 "In the client-server model, the client is:",
 "The computer that provides services",
 "The computer or device that requests services",
 "The internet connection itself",
 "The power supply","B"),

("SOA & Managed Services","Client-Server Model",
 "In the client-server model, the server is:",
 "The device that only receives data",
 "The computer that provides services and resources to clients",
 "A monitor display",
 "A keyboard","B"),

("SOA & Managed Services","Client-Server Model",
 "A web browser accessing a website is an example of:",
 "Peer-to-peer networking",
 "Client-server architecture",
 "No networking at all",
 "Physical mail delivery","B"),

("SOA & Managed Services","Client-Server Model",
 "In client-server architecture, communication occurs over:",
 "Postal service",
 "A computer network using protocols",
 "Physical touch only",
 "Paper notes","B"),

("SOA & Managed Services","Client-Server Model",
 "HTTP is a protocol used in client-server communication for:",
 "Power supply management",
 "Web page requests and responses",
 "Keyboard input only",
 "Printer management only","B"),

("SOA & Managed Services","Client-Server Model",
 "A database server provides:",
 "Physical printing services",
 "Data storage and retrieval services to client applications",
 "Only email forwarding",
 "Only display output","B"),

("SOA & Managed Services","Client-Server Model",
 "The client-server model is the basis for:",
 "Standalone calculators",
 "Most internet and networked applications",
 "Physical board games",
 "Manual typewriters","B"),

("SOA & Managed Services","Client-Server Model",
 "A file server in a client-server network:",
 "Stores and manages files that clients can access",
 "Only prints files",
 "Only deletes files",
 "Has no storage capability","A"),

("SOA & Managed Services","Client-Server Model",
 "A mail server handles:",
 "Physical postal mail",
 "Sending, receiving, and storing email messages",
 "Only web browsing",
 "Only file storage","B"),

("SOA & Managed Services","Client-Server Model",
 "Client-server differs from peer-to-peer in that:",
 "All computers are equal in client-server",
 "There are dedicated roles: clients request, servers provide",
 "No network is used in client-server",
 "Servers request services from clients","B"),

# ── CLIENT & GUI ── Client Definition ──
("Client & GUI","Client Definition",
 "In computing, a client is:",
 "A device or application that requests services from a server",
 "A physical store customer",
 "The power outlet in a wall",
 "A type of programming language","A"),

("Client & GUI","Client Definition",
 "A thin client depends heavily on:",
 "Its own processor for all tasks",
 "A remote server for processing and storage",
 "No external resources",
 "Only battery power","B"),

("Client & GUI","Client Definition",
 "A thick client (fat client) performs:",
 "No processing locally",
 "Significant processing locally on the device",
 "Only network functions",
 "Only display functions","B"),

("Client & GUI","Client Definition",
 "A web browser is an example of a:",
 "Server","Client application","Hardware device","Power supply","B"),

("Client & GUI","Client Definition",
 "An email client like Outlook is called a client because it:",
 "Provides email services to others",
 "Requests email services from a mail server",
 "Manufactures hardware",
 "Only displays images","B"),

("Client & GUI","Client Definition",
 "A mobile app requesting data from a cloud API is functioning as a:",
 "Server","Client","Router","Switch","B"),

("Client & GUI","Client Definition",
 "Client software typically provides:",
 "A user interface for interacting with services",
 "No interface at all",
 "Only hardware control",
 "Only power management","A"),

("Client & GUI","Client Definition",
 "In a client-server database system, the client application:",
 "Stores all the data itself",
 "Sends queries to the database server and displays results",
 "Has no connection to any server",
 "Acts as the database engine","B"),

("Client & GUI","Client Definition",
 "The term 'client' in IT does NOT refer to:",
 "A web browser on a user's machine",
 "An app requesting data from a server",
 "The physical building of a company",
 "A thin client terminal","C"),

("Client & GUI","Client Definition",
 "Zero client computing means:",
 "The client device has almost no local OS or storage",
 "No clients exist at all",
 "The server has zero clients connected",
 "No computing takes place","A"),

("Client & GUI","Client Definition",
 "A POS terminal in a shop connecting to a central server is a:",
 "Server","Client device","Router","Modem","B"),

("Client & GUI","Client Definition",
 "Client-side processing happens on:",
 "The server only","The user's device","The cloud provider's headquarters","The ISP's office","B"),

# ── GUI Definition ──
("Client & GUI","GUI Definition",
 "GUI stands for:",
 "Graphical User Interface","General Utility Input","Global User Integration","Green Universal Interface","A"),

("Client & GUI","GUI Definition",
 "A GUI allows users to interact with a computer using:",
 "Only text commands",
 "Visual elements like icons, buttons, and windows",
 "Only voice commands",
 "Physical switches only","B"),

("Client & GUI","GUI Definition",
 "Which operating system popularized the GUI?",
 "MS-DOS","Apple Macintosh and later Windows","Unix command line only","Linux terminal only","B"),

("Client & GUI","GUI Definition",
 "A GUI is an alternative to a:",
 "Mouse","Command-line interface (CLI)","Monitor","Internet connection","B"),

("Client & GUI","GUI Definition",
 "Which of the following is a GUI element?",
 "A text-only terminal prompt",
 "A clickable button on screen",
 "A punch card",
 "A paper form","B"),

("Client & GUI","GUI Definition",
 "WIMP in GUI design stands for:",
 "Windows, Icons, Menus, Pointer","Wide Internet Main Protocol","Wireless Input Management Program","Web Interface Module Platform","A"),

("Client & GUI","GUI Definition",
 "A GUI makes computing more accessible because:",
 "Users need to memorize complex commands",
 "Visual elements make interaction intuitive for non-technical users",
 "It removes all visual elements",
 "It requires advanced programming knowledge","B"),

("Client & GUI","GUI Definition",
 "Which company developed the first commercial GUI-based computer?",
 "IBM","Xerox (Xerox Alto)","Microsoft","Dell","B"),

("Client & GUI","GUI Definition",
 "A desktop icon in a GUI represents:",
 "Nothing",
 "A shortcut to a file, folder, or application",
 "Only decorative artwork",
 "The pixel density of the screen","B"),

("Client & GUI","GUI Definition",
 "Scroll bars, checkboxes, and dropdown menus are examples of:",
 "CLI commands","GUI widgets or elements","Hardware components","Network protocols","B"),

("Client & GUI","GUI Definition",
 "The GUI on a smartphone includes:",
 "Only text prompts","Touch-based icons, swipe gestures, and visual menus","Only keyboard input","Only voice commands","B"),

("Client & GUI","GUI Definition",
 "A GUI requires which input devices?",
 "Only a printer","Mouse, keyboard, touchscreen, or similar pointing devices","Only a scanner","Only a microphone","B"),

# ── Application Layer Role ──
("Client & GUI","Application Layer Role",
 "The application layer in the OSI model is responsible for:",
 "Physical cable management",
 "Providing network services directly to end-user applications",
 "Only routing packets",
 "Only electrical signal transmission","B"),

("Client & GUI","Application Layer Role",
 "The application layer is which layer of the OSI model?",
 "Layer 1","Layer 4","Layer 7","Layer 3","C"),

("Client & GUI","Application Layer Role",
 "Which protocol operates at the application layer?",
 "TCP","IP","HTTP","Ethernet","C"),

("Client & GUI","Application Layer Role",
 "FTP (File Transfer Protocol) operates at the:",
 "Physical layer","Data link layer","Application layer","Network layer","C"),

("Client & GUI","Application Layer Role",
 "SMTP, used for sending emails, operates at the:",
 "Transport layer","Application layer","Physical layer","Session layer","B"),

("Client & GUI","Application Layer Role",
 "DNS operates at the application layer to:",
 "Deliver physical mail",
 "Translate domain names to IP addresses",
 "Manage network cables",
 "Regulate power supply","B"),

("Client & GUI","Application Layer Role",
 "The application layer serves as the interface between:",
 "Hardware and electricity",
 "The network and the user's application software",
 "Two physical cables",
 "The keyboard and mouse only","B"),

("Client & GUI","Application Layer Role",
 "Web browsers interact with web servers at the:",
 "Physical layer","Transport layer","Application layer","Data link layer","C"),

("Client & GUI","Application Layer Role",
 "HTTPS at the application layer provides:",
 "Only speed improvement",
 "Secure encrypted communication for web traffic",
 "Only audio streaming",
 "Only file deletion","B"),

("Client & GUI","Application Layer Role",
 "Telnet and SSH are application layer protocols for:",
 "Physical hardware testing",
 "Remote login and command execution on distant computers",
 "Power management",
 "Disk formatting only","B"),

("Client & GUI","Application Layer Role",
 "POP3 and IMAP at the application layer are used for:",
 "Routing network traffic",
 "Retrieving emails from a mail server",
 "Managing physical cables",
 "Compressing video files","B"),

("Client & GUI","Application Layer Role",
 "SNMP at the application layer is used for:",
 "Sending text messages",
 "Network management and monitoring",
 "Playing games",
 "Printing documents","B"),

# ── Client-Server Interaction ──
("Client & GUI","Client-Server Interaction",
 "In client-server interaction, the client typically initiates:",
 "Nothing","A request to the server","The server's hardware setup","The network cable connection","B"),

("Client & GUI","Client-Server Interaction",
 "The server responds to the client with:",
 "The requested data or service",
 "A physical package",
 "A phone call",
 "A postal letter","A"),

("Client & GUI","Client-Server Interaction",
 "Request-response is the fundamental pattern of:",
 "Physical mail delivery",
 "Client-server interaction",
 "Power generation",
 "Hardware manufacturing","B"),

("Client & GUI","Client-Server Interaction",
 "When you type a URL in a browser, the browser sends an HTTP request to:",
 "Your printer","The web server hosting that website","Your keyboard","Your mouse","B"),

("Client & GUI","Client-Server Interaction",
 "The web server processes the request and sends back:",
 "A physical document","An HTTP response (typically an HTML page)","A text message to your phone","An email","B"),

("Client & GUI","Client-Server Interaction",
 "Stateless client-server interaction means:",
 "The server stores every client interaction permanently",
 "Each request from the client is treated independently",
 "The client and server share memory",
 "No requests can be made","B"),

("Client & GUI","Client-Server Interaction",
 "Cookies are used in web client-server interaction to:",
 "Bake digital cakes",
 "Maintain state information between stateless HTTP requests",
 "Delete all user data",
 "Slow down the internet","B"),

("Client & GUI","Client-Server Interaction",
 "An API allows client-server interaction through:",
 "Physical meetings",
 "Defined methods and data formats for exchanging information",
 "Only voice calls",
 "Postal correspondence","B"),

("Client & GUI","Client-Server Interaction",
 "Load balancing in client-server systems distributes:",
 "Physical weight of servers",
 "Client requests across multiple servers to optimize performance",
 "Electricity bills among employees",
 "Paper documents among departments","B"),

("Client & GUI","Client-Server Interaction",
 "In a three-tier architecture, the tiers are:",
 "Monitor, keyboard, mouse",
 "Presentation (client), application logic, and database",
 "Electricity, water, gas",
 "Input, output, storage only","B"),

# ── MEMORY ── Primary Memory (RAM) ──
("Memory","Primary Memory (RAM)",
 "RAM stands for:",
 "Random Access Memory","Read All Memory","Run Application Module","Rapid Access Method","A"),

("Memory","Primary Memory (RAM)",
 "RAM is classified as:",
 "Secondary storage","Primary (main) memory","Output device","Input device","B"),

("Memory","Primary Memory (RAM)",
 "RAM is volatile, which means:",
 "Data is retained permanently",
 "Data is lost when power is turned off",
 "Data can never be written",
 "Data is always encrypted","B"),

("Memory","Primary Memory (RAM)",
 "RAM provides:",
 "Permanent storage for files",
 "Temporary fast storage for currently running programs and data",
 "Only display output",
 "Only sound output","B"),

("Memory","Primary Memory (RAM)",
 "Which type of RAM stores each bit in a tiny capacitor?",
 "SRAM","DRAM","ROM","Cache","B"),

("Memory","Primary Memory (RAM)",
 "SRAM (Static RAM) is:",
 "Slower than DRAM","Faster than DRAM but more expensive","Not a type of memory","A storage device","B"),

("Memory","Primary Memory (RAM)",
 "DRAM stands for:",
 "Dynamic Random Access Memory","Dual Read Application Module","Direct Resource Access Memory","Data Recovery Automated Method","A"),

("Memory","Primary Memory (RAM)",
 "More RAM in a computer generally means:",
 "Slower performance","Ability to run more programs simultaneously with better performance","More permanent storage","Louder operation","B"),

("Memory","Primary Memory (RAM)",
 "A common RAM capacity for modern PCs is:",
 "64 KB","512 KB","8 GB or 16 GB","1 byte","C"),

("Memory","Primary Memory (RAM)",
 "The CPU accesses data from RAM:",
 "Very slowly, taking minutes","Very quickly, in nanoseconds","Not at all","Only once per day","B"),

("Memory","Primary Memory (RAM)",
 "DDR in DDR RAM stands for:",
 "Double Data Rate","Dual Drive Reader","Direct Disk Recovery","Dynamic Data Resource","A"),

("Memory","Primary Memory (RAM)",
 "DDR4 and DDR5 are types of:",
 "Hard disk drives","RAM modules","Output devices","Operating systems","B"),

("Memory","Primary Memory (RAM)",
 "RAM sticks are typically inserted into:",
 "USB ports","DIMM slots on the motherboard","HDMI ports","Power sockets","B"),

("Memory","Primary Memory (RAM)",
 "When you open an application on your computer, it loads into:",
 "The hard drive only","RAM for fast access","The printer","The monitor","B"),

("Memory","Primary Memory (RAM)",
 "If a computer runs out of RAM during operation, the OS may use:",
 "Extra monitors",
 "Virtual memory (swap space on the hard drive)",
 "Additional power supply",
 "Physical paper for storage","B"),

# ── Secondary Memory ──
("Memory","Secondary Memory",
 "Secondary memory provides:",
 "Temporary storage that is cleared when power is off",
 "Permanent or long-term storage for data and programs",
 "Only processing capability",
 "Only display output","B"),

("Memory","Secondary Memory",
 "Secondary memory is:",
 "Volatile","Non-volatile","A type of RAM","An input device","B"),

("Memory","Secondary Memory",
 "Which of the following is a type of secondary memory?",
 "RAM","Cache memory","Hard disk drive","CPU register","C"),

("Memory","Secondary Memory",
 "Secondary memory is slower than primary memory because:",
 "It uses faster technology",
 "It uses mechanical or slower electronic storage media",
 "It has no storage capability",
 "It connects via faster buses","B"),

("Memory","Secondary Memory",
 "SSD stands for:",
 "Solid State Drive","Standard Storage Device","Secondary System Disk","Static Storage Drive","A"),

("Memory","Secondary Memory",
 "An SSD is faster than an HDD because:",
 "It has more moving parts",
 "It has no mechanical moving parts and uses flash memory",
 "It uses magnetic platters",
 "It requires more power","B"),

("Memory","Secondary Memory",
 "CD, DVD, and Blu-ray are types of:",
 "Primary memory","Secondary optical storage","Input devices","Output devices only","B"),

("Memory","Secondary Memory",
 "USB flash drives are:",
 "Primary memory devices","Portable secondary storage devices","Processing units","Display devices","B"),

("Memory","Secondary Memory",
 "Secondary memory retains data even when:",
 "The computer is running only",
 "The computer is powered off",
 "The keyboard is connected",
 "The monitor is on","B"),

("Memory","Secondary Memory",
 "A typical modern HDD capacity ranges from:",
 "1 KB to 100 KB","500 GB to several TB","1 byte to 10 bytes","100 bits","B"),

("Memory","Secondary Memory",
 "External hard drives connect to computers via:",
 "DIMM slots","USB or Thunderbolt ports","RAM slots","CPU sockets","B"),

("Memory","Secondary Memory",
 "SD cards used in cameras and phones are:",
 "Primary memory","Secondary flash storage","Processing chips","Sound cards","B"),

# ── Magnetic Tape ──
("Memory","Magnetic Tape",
 "Magnetic tape stores data using:",
 "Optical laser technology",
 "A magnetizable coating on a thin plastic strip",
 "Electrical capacitors",
 "Light patterns","B"),

("Memory","Magnetic Tape",
 "Magnetic tape uses which type of access?",
 "Random access","Sequential access","Immediate access","Parallel access","B"),

("Memory","Magnetic Tape",
 "Magnetic tape is commonly used for:",
 "Running software applications",
 "Data backup and archival storage",
 "Real-time gaming",
 "Display output","B"),

("Memory","Magnetic Tape",
 "A disadvantage of magnetic tape is:",
 "Very high cost",
 "Slow access time due to sequential reading",
 "It cannot store data at all",
 "It is too fast","B"),

("Memory","Magnetic Tape",
 "An advantage of magnetic tape is:",
 "Fast random access",
 "Very low cost per gigabyte for large-scale storage",
 "Instant data retrieval",
 "No physical medium needed","B"),

("Memory","Magnetic Tape",
 "LTO (Linear Tape-Open) is a type of:",
 "Optical disc","Magnetic tape format used for backup","RAM module","CPU chip","B"),

("Memory","Magnetic Tape",
 "Magnetic tape is most suitable for:",
 "Frequently accessed data",
 "Rarely accessed archival data that needs long-term preservation",
 "Running operating systems",
 "Displaying graphics","B"),

("Memory","Magnetic Tape",
 "Large organizations store magnetic tape backups in:",
 "The cloud only",
 "Offsite secure storage facilities",
 "On employee desks",
 "In recycling bins","B"),

("Memory","Magnetic Tape",
 "Modern LTO tapes can store:",
 "A few kilobytes only",
 "Several terabytes of data on a single cartridge",
 "Only 1 MB",
 "No data at all","B"),

("Memory","Magnetic Tape",
 "Magnetic tape was first used for computer data storage in the:",
 "2010s","1950s","1990s","2000s","B"),

# ── Hard Disk ──
("Memory","Hard Disk",
 "A hard disk drive (HDD) stores data on:",
 "Magnetic tape reels",
 "Rapidly spinning magnetic platters",
 "Optical discs",
 "Paper cards","B"),

("Memory","Hard Disk",
 "The read/write head of an HDD:",
 "Touches the platter directly",
 "Floats just above the spinning platter",
 "Is located inside the RAM",
 "Is the same as the CPU","B"),

("Memory","Hard Disk",
 "HDD speed is often measured in:",
 "Watts","RPM (Revolutions Per Minute)","Lumens","Decibels","B"),

("Memory","Hard Disk",
 "A common HDD speed is:",
 "100 RPM","5400 or 7200 RPM","1 million RPM","10 RPM","B"),

("Memory","Hard Disk",
 "Hard disk drives are examples of:",
 "Primary memory","Secondary storage devices","Input devices","Output devices","B"),

("Memory","Hard Disk",
 "Disk fragmentation in an HDD means:",
 "The disk is physically broken",
 "Files are stored in non-contiguous sectors, slowing access",
 "The disk has too much free space",
 "The disk is perfectly organized","B"),

("Memory","Hard Disk",
 "Defragmentation is the process of:",
 "Breaking files into smaller pieces",
 "Reorganizing fragmented data on a disk for faster access",
 "Deleting all files",
 "Formatting the drive","B"),

("Memory","Hard Disk",
 "SATA is a common interface for connecting HDDs to the:",
 "Printer","Motherboard","Mouse","Speaker","B"),

("Memory","Hard Disk",
 "HDD platters are made of:",
 "Plastic only","Glass or aluminum coated with magnetic material","Paper","Wood","B"),

("Memory","Hard Disk",
 "The capacity of a typical modern internal HDD is:",
 "100 MB","1 TB to 4 TB or more","10 bytes","5 KB","B"),

("Memory","Hard Disk",
 "A head crash on an HDD occurs when:",
 "The user drops the mouse",
 "The read/write head contacts the platter surface, causing damage",
 "The monitor turns off",
 "The keyboard stops working","B"),

("Memory","Hard Disk",
 "HDDs are being increasingly replaced by SSDs because:",
 "HDDs are smaller in size",
 "SSDs are faster, more durable, and have no moving parts",
 "HDDs are more expensive",
 "SSDs have more moving parts","B"),

# ── Floppy Disk ──
("Memory","Floppy Disk",
 "A floppy disk is a type of:",
 "Primary memory","Removable secondary storage medium","Processing unit","Output device","B"),

("Memory","Floppy Disk",
 "The standard 3.5-inch floppy disk had a capacity of:",
 "1 TB","1.44 MB","500 GB","100 GB","B"),

("Memory","Floppy Disk",
 "Floppy disks store data using:",
 "Optical laser technology","Magnetic coating on a flexible disk","Flash memory","Holographic storage","B"),

("Memory","Floppy Disk",
 "Floppy disks were widely used during the:",
 "2020s","1980s and 1990s","2010s","1940s","B"),

("Memory","Floppy Disk",
 "Floppy disks have largely been replaced by:",
 "Larger floppy disks",
 "USB flash drives, CDs, and cloud storage",
 "Paper notebooks",
 "Typewriters","B"),

("Memory","Floppy Disk",
 "The 'Save' icon in many applications resembles a:",
 "Hard drive","Floppy disk","USB drive","CD","B"),

("Memory","Floppy Disk",
 "A floppy disk drive was abbreviated as:",
 "HDD","FDD","SSD","DVD","B"),

("Memory","Floppy Disk",
 "The earlier 5.25-inch floppy disk was:",
 "Smaller than the 3.5-inch disk",
 "Larger and more flexible than the 3.5-inch disk",
 "Made of metal",
 "Used in modern computers","B"),

("Memory","Floppy Disk",
 "A floppy disk is portable because:",
 "It weighs several kilograms",
 "It is small and lightweight, easily carried between computers",
 "It requires a power outlet",
 "It needs internet to function","B"),

("Memory","Floppy Disk",
 "Compared to modern USB drives, floppy disks have:",
 "Greater storage capacity",
 "Much less storage capacity",
 "Faster transfer speeds",
 "Better durability","B"),

# ── RAM vs Secondary Memory ──
("Memory","RAM vs Secondary Memory",
 "The main difference between RAM and secondary memory is:",
 "RAM is permanent, secondary is temporary",
 "RAM is volatile and fast, secondary memory is non-volatile and slower",
 "Both are exactly the same",
 "Secondary memory is faster than RAM","B"),

("Memory","RAM vs Secondary Memory",
 "Data in RAM is lost when power goes off, but data in a hard disk is:",
 "Also lost immediately","Retained even without power","Transferred to the printer","Erased automatically","B"),

("Memory","RAM vs Secondary Memory",
 "CPU accesses RAM in nanoseconds, while accessing a hard disk takes:",
 "Nanoseconds too","Milliseconds (much slower)","Hours","Days","B"),

("Memory","RAM vs Secondary Memory",
 "RAM is used for storing:",
 "Permanent files only",
 "Currently running programs and active data",
 "Archived data for years",
 "Backup copies only","B"),

("Memory","RAM vs Secondary Memory",
 "Secondary memory is used for storing:",
 "Only running programs",
 "Files, applications, and the operating system permanently",
 "Only display settings",
 "Only temporary cache","B"),

("Memory","RAM vs Secondary Memory",
 "Which is more expensive per gigabyte?",
 "Hard disk drive","RAM","Floppy disk","Magnetic tape","B"),

("Memory","RAM vs Secondary Memory",
 "A computer needs both RAM and secondary storage because:",
 "RAM alone is too expensive for permanent storage",
 "RAM provides speed for active tasks while secondary memory stores data permanently",
 "Secondary memory is too fast",
 "They serve identical purposes","B"),

("Memory","RAM vs Secondary Memory",
 "When a computer boots up, the OS loads from secondary storage into:",
 "The monitor","RAM","The printer","The network cable","B"),

("Memory","RAM vs Secondary Memory",
 "Typical RAM capacity is measured in GB, while hard disk capacity is measured in:",
 "Bytes only","GB to TB","Bits only","KB only","B"),

("Memory","RAM vs Secondary Memory",
 "Virtual memory is a technique that uses secondary storage to:",
 "Replace RAM entirely",
 "Extend the effective size of RAM when physical RAM is full",
 "Speed up the hard drive",
 "Delete unused files","B"),

("Memory","RAM vs Secondary Memory",
 "Cache memory is even faster than RAM and sits between:",
 "The power supply and the monitor",
 "The CPU and RAM to speed up data access",
 "The hard drive and the USB port",
 "The keyboard and mouse","B"),

("Memory","RAM vs Secondary Memory",
 "Which statement is TRUE?",
 "RAM has greater capacity than hard drives",
 "Hard drives have greater capacity but are slower than RAM",
 "RAM and hard drives are equally fast",
 "Hard drives are always faster than RAM","B"),

("Memory","RAM vs Secondary Memory",
 "ROM (Read-Only Memory) is different from RAM because ROM is:",
 "Volatile","Non-volatile and retains data without power","Faster than RAM","Used only for display","B"),

("Memory","RAM vs Secondary Memory",
 "BIOS is stored in ROM because it needs to be available:",
 "Only when the user requests",
 "Immediately when the computer starts, before the OS loads",
 "Only during shutdown",
 "Only during printing","B"),
]
