# Section 1 Questions 201-400: Cloud Deployment, Virtualization, Utility & Grid Computing
# Format: (topic, subtopic, question, optA, optB, optC, optD, answer)

def get_questions():
    return [
# ── CLOUD DEPLOYMENT MODELS ── Public Cloud ──
("Cloud Deployment Models","Public Cloud",
 "A public cloud is operated by:",
 "A single private company for its own use only",
 "A third-party provider and shared among multiple organizations",
 "Only government agencies",
 "A single user at home","B"),

("Cloud Deployment Models","Public Cloud",
 "Which is a characteristic of a public cloud?",
 "Resources are shared among multiple tenants",
 "Only one company can use it",
 "It has no internet connectivity",
 "It requires physical presence at the data center","A"),

("Cloud Deployment Models","Public Cloud",
 "AWS, Azure, and Google Cloud are examples of:",
 "Private clouds","Hybrid clouds","Public clouds","Community clouds","C"),

("Cloud Deployment Models","Public Cloud",
 "In a public cloud, infrastructure costs are:",
 "Borne entirely by each user separately",
 "Shared among all users, reducing individual costs",
 "Free for everyone always",
 "Not applicable","B"),

("Cloud Deployment Models","Public Cloud",
 "Public cloud services are accessible via:",
 "Private cables only","The public internet","Carrier pigeons","Postal mail","B"),

("Cloud Deployment Models","Public Cloud",
 "Which is an advantage of public cloud?",
 "No scalability","High upfront hardware investment","Low cost and high scalability","Limited availability","C"),

("Cloud Deployment Models","Public Cloud",
 "Public clouds are best suited for:",
 "Highly confidential military data only",
 "General-purpose workloads and applications with variable demand",
 "Applications that never need the internet",
 "Single-user desktop operations only","B"),

("Cloud Deployment Models","Public Cloud",
 "In a public cloud, maintenance of hardware is done by:",
 "The end user","The cloud service provider","The local ISP","Nobody","B"),

("Cloud Deployment Models","Public Cloud",
 "A disadvantage of public cloud is:",
 "Lower cost than private cloud",
 "Less control over data and security compared to private cloud",
 "Too much control given to users",
 "No availability concerns","B"),

("Cloud Deployment Models","Public Cloud",
 "Multi-tenancy in public cloud means:",
 "Only one customer uses the infrastructure",
 "Multiple customers share the same physical infrastructure",
 "Each customer has a dedicated building",
 "No customers use the infrastructure","B"),

("Cloud Deployment Models","Public Cloud",
 "Public cloud pricing is typically:",
 "Fixed annual fee with no flexibility",
 "Pay-as-you-go based on usage",
 "Completely free always",
 "Based on company size only","B"),

("Cloud Deployment Models","Public Cloud",
 "A startup with limited budget would likely choose:",
 "Building its own data center",
 "Public cloud for its low initial cost",
 "No cloud at all",
 "A mainframe computer","B"),

("Cloud Deployment Models","Public Cloud",
 "Public cloud resources can be scaled:",
 "Only downward","Rapidly up or down as needed","Never","Only once per year","B"),

("Cloud Deployment Models","Public Cloud",
 "Which compliance concern exists with public clouds?",
 "Data may be stored in different geographic regions",
 "Data is always in the same building as the user",
 "No security measures are in place",
 "Public clouds do not store any data","A"),

("Cloud Deployment Models","Public Cloud",
 "Public clouds offer high availability through:",
 "Single server deployment",
 "Redundant infrastructure across multiple data centers",
 "Handwritten backup systems",
 "One backup per decade","B"),

# ── Private Cloud ──
("Cloud Deployment Models","Private Cloud",
 "A private cloud is used by:",
 "The general public","A single organization exclusively","Any random user","Multiple competing companies together","B"),

("Cloud Deployment Models","Private Cloud",
 "Private clouds offer greater:",
 "Cost savings than public cloud always",
 "Control over security and data",
 "Number of users",
 "Internet speed","B"),

("Cloud Deployment Models","Private Cloud",
 "Private cloud infrastructure can be hosted:",
 "Only on-premises","Only off-premises","On-premises or by a third-party provider for exclusive use","Only in public data centers","C"),

("Cloud Deployment Models","Private Cloud",
 "Which industry commonly uses private cloud for data compliance?",
 "Fast food restaurants","Banking and healthcare","Toy manufacturing","Agriculture only","B"),

("Cloud Deployment Models","Private Cloud",
 "A private cloud is more expensive than public cloud because:",
 "It uses cheaper hardware",
 "The organization bears the full cost of infrastructure",
 "It has no cost at all",
 "Public cloud providers subsidize it","B"),

("Cloud Deployment Models","Private Cloud",
 "OpenStack is a platform used to build:",
 "Public clouds only","Private clouds","Mobile apps","Video games","B"),

("Cloud Deployment Models","Private Cloud",
 "VMware vSphere is commonly used in:",
 "Public cloud only","Private cloud environments","Social media","Web browsers","B"),

("Cloud Deployment Models","Private Cloud",
 "A private cloud provides better:",
 "Multi-tenancy","Customization and control","Free services","Public accessibility","B"),

("Cloud Deployment Models","Private Cloud",
 "Data sovereignty concerns are better addressed by:",
 "Public cloud","Private cloud","No cloud","Shared hosting with strangers","B"),

("Cloud Deployment Models","Private Cloud",
 "Private cloud is suitable for organizations with:",
 "No data at all",
 "Strict regulatory and compliance requirements",
 "No budget for IT",
 "Very few employees only","B"),

("Cloud Deployment Models","Private Cloud",
 "In a private cloud, who manages the infrastructure?",
 "Any random person",
 "The organization's IT team or a dedicated provider",
 "End users with no IT knowledge",
 "The general public","B"),

("Cloud Deployment Models","Private Cloud",
 "A key disadvantage of private cloud is:",
 "High security","Greater control","Higher cost and complexity to manage","Better compliance","C"),

("Cloud Deployment Models","Private Cloud",
 "Private cloud can be managed using:",
 "Only manual processes",
 "Automation tools like VMware, OpenStack, or Hyper-V",
 "Only paper records",
 "Only fax machines","B"),

("Cloud Deployment Models","Private Cloud",
 "Which of the following is NOT a feature of private cloud?",
 "Dedicated resources for one organization",
 "Shared infrastructure with the public",
 "Enhanced security controls",
 "Customizable configurations","B"),

("Cloud Deployment Models","Private Cloud",
 "Government agencies often prefer private cloud for:",
 "Lower costs","Enhanced data security and compliance","Faster internet","Free services","B"),

# ── Hybrid Cloud ──
("Cloud Deployment Models","Hybrid Cloud",
 "A hybrid cloud combines:",
 "Only public clouds","Only private clouds","Both public and private cloud environments","No cloud at all","C"),

("Cloud Deployment Models","Hybrid Cloud",
 "The main advantage of a hybrid cloud is:",
 "It is always free",
 "Flexibility to move workloads between public and private environments",
 "It has no internet requirement",
 "It only works offline","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "In a hybrid cloud, sensitive data can be kept in the:",
 "Public cloud only","Private cloud while less-sensitive workloads run on the public cloud","Neither public nor private","On paper only","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Cloud bursting is a concept related to:",
 "Private cloud only","Hybrid cloud","Public cloud only","No cloud","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Cloud bursting means:",
 "A cloud server physically exploding",
 "An application running in a private cloud bursts into the public cloud during demand spikes",
 "Deleting all cloud data",
 "Shutting down all servers","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "A hospital might use hybrid cloud to keep patient records private while using public cloud for:",
 "Storing genetic data publicly",
 "General website hosting and non-sensitive applications",
 "Nothing at all",
 "Sharing patient data with everyone","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Hybrid cloud offers a balance between:",
 "Cost and no computing at all",
 "Security of private cloud and scalability of public cloud",
 "Speed and no internet",
 "Free storage and paid hardware","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Orchestration in hybrid cloud refers to:",
 "Playing musical instruments",
 "Coordinating workloads across public and private clouds",
 "Only managing public cloud",
 "Only managing hardware","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Which company offers Azure Arc for hybrid cloud management?",
 "Amazon","Google","Microsoft","IBM","C"),

("Cloud Deployment Models","Hybrid Cloud",
 "AWS Outposts enables hybrid cloud by:",
 "Deleting all public cloud data",
 "Extending AWS infrastructure to on-premises environments",
 "Removing all cloud services",
 "Only providing software updates","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "A hybrid cloud strategy requires careful management of:",
 "Only one environment",
 "Data movement, security, and compliance across environments",
 "Paper records only",
 "Only local area networks","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Which is a challenge of hybrid cloud?",
 "Too much simplicity",
 "Complexity in managing multiple environments",
 "No cost involved",
 "Too few options","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "A retail company using private cloud for payment processing and public cloud for website hosting is using:",
 "Public cloud only","Private cloud only","Hybrid cloud","No cloud","C"),

("Cloud Deployment Models","Hybrid Cloud",
 "Hybrid cloud helps organizations avoid:",
 "Using any technology",
 "Vendor lock-in by distributing workloads",
 "Using the internet",
 "Having any security","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Inter-cloud connectivity in hybrid cloud is typically achieved via:",
 "Postal mail","VPN, dedicated connections, or APIs","Fax only","Physical delivery of hard drives","B"),

# ── Use-case Based Differences ──
("Cloud Deployment Models","Use-case Based Differences",
 "A small blog website with variable traffic is best suited for:",
 "Private cloud","Public cloud","No cloud","Mainframe computer","B"),

("Cloud Deployment Models","Use-case Based Differences",
 "A defense organization handling classified data should prefer:",
 "Public cloud","Private cloud","Social media servers","Shared hosting","B"),

("Cloud Deployment Models","Use-case Based Differences",
 "An e-commerce company with seasonal traffic spikes should consider:",
 "Only private cloud","Only public cloud","Hybrid cloud","No cloud at all","C"),

("Cloud Deployment Models","Use-case Based Differences",
 "A research university sharing public datasets while securing proprietary research should use:",
 "Public cloud only","Private cloud only","Hybrid cloud","Community cloud","C"),

("Cloud Deployment Models","Use-case Based Differences",
 "For rapid prototyping of new applications, which cloud is most cost-effective?",
 "Private cloud","Public cloud","No cloud","Dedicated hardware","B"),

("Cloud Deployment Models","Use-case Based Differences",
 "A financial institution needing strict data residency compliance would prefer:",
 "Public cloud","Private or hybrid cloud","Social media hosting","Free hosting","B"),

("Cloud Deployment Models","Use-case Based Differences",
 "A global media streaming company needing massive scalability would primarily use:",
 "Private cloud only","Public cloud","Physical DVD distribution","Local servers only","B"),

("Cloud Deployment Models","Use-case Based Differences",
 "A healthcare company needing to store sensitive patient data while using cloud analytics should use:",
 "Public cloud for everything","Private cloud for everything","Hybrid cloud","No cloud at all","C"),

("Cloud Deployment Models","Use-case Based Differences",
 "For disaster recovery, a company might replicate private cloud data to:",
 "Nowhere","A public cloud region","A printed backup","A single USB drive","B"),

("Cloud Deployment Models","Use-case Based Differences",
 "Community cloud is used by organizations with:",
 "Nothing in common","Shared concerns such as compliance or industry regulations","Competing business interests","No computing needs","B"),

# ── VIRTUALIZATION & ARCHITECTURE ── Virtualization Definition ──
("Virtualization & Architecture","Virtualization Definition",
 "Virtualization is the process of creating a:",
 "Physical copy of hardware",
 "Virtual version of something such as a server, storage, or network",
 "Paper model of a computer",
 "Wooden replica of a server","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Virtualization allows multiple operating systems to run on:",
 "Multiple separate physical machines each",
 "A single physical machine simultaneously",
 "No machine at all",
 "Only mobile phones","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Which of the following is a benefit of virtualization?",
 "Increased hardware purchase costs",
 "Better utilization of physical hardware resources",
 "Slower performance always",
 "More physical servers needed","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Server virtualization divides a single physical server into:",
 "Smaller physical servers",
 "Multiple isolated virtual servers",
 "Paper copies",
 "Backup tapes","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Virtualization helps reduce:",
 "Software quality","Hardware costs and physical space requirements","Internet speed","Data accuracy","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Desktop virtualization allows users to:",
 "Access a virtual desktop environment hosted on a remote server",
 "Use only physical keyboards",
 "Avoid using any computer",
 "Only print documents","A"),

("Virtualization & Architecture","Virtualization Definition",
 "Network virtualization combines:",
 "Physical cables into one cable",
 "Hardware and software network resources into a single virtual network",
 "Paper maps into a digital map",
 "Only wireless signals","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Storage virtualization pools physical storage from multiple devices into:",
 "One large physical disk",
 "A single virtual storage unit managed centrally",
 "A printed storage list",
 "A filing cabinet","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Virtualization is a foundational technology for:",
 "Traditional mainframe computing only","Cloud computing","Typewriter operations","Manual accounting","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Which company is a major provider of virtualization software?",
 "Nokia","VMware","Kodak","Yamaha","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Application virtualization allows an application to run in an environment:",
 "Separated from the underlying operating system's full installation",
 "Only on the developer's machine",
 "Only on super computers",
 "Without electricity","A"),

("Virtualization & Architecture","Virtualization Definition",
 "Without virtualization, each workload typically requires:",
 "No hardware","Its own dedicated physical server","A pencil and paper","Only a monitor","B"),

# ── Hypervisor Definition ──
("Virtualization & Architecture","Hypervisor Definition",
 "A hypervisor is software that:",
 "Deletes virtual machines",
 "Creates and manages virtual machines on physical hardware",
 "Only prints documents",
 "Manufactures physical servers","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "Another name for a hypervisor is:",
 "Virtual Machine Monitor (VMM)","Virtual Private Network","Very Massive Memory","Visual Machine Module","A"),

("Virtualization & Architecture","Hypervisor Definition",
 "A Type 1 hypervisor runs:",
 "On top of an existing operating system",
 "Directly on the physical hardware (bare-metal)",
 "Only in web browsers",
 "Only on mobile phones","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "A Type 2 hypervisor runs:",
 "Directly on hardware",
 "On top of an existing host operating system",
 "Without any hardware",
 "Only on embedded systems","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "VMware ESXi is an example of a:",
 "Type 2 hypervisor","Type 1 (bare-metal) hypervisor","Web browser","Programming language","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "Oracle VirtualBox is an example of a:",
 "Type 1 hypervisor","Type 2 hypervisor","Physical server","Network switch","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "Microsoft Hyper-V can function as a:",
 "Type 1 hypervisor","Web browser","Email client","Word processor","A"),

("Virtualization & Architecture","Hypervisor Definition",
 "The hypervisor allocates physical resources such as CPU, memory, and storage to:",
 "Paper files","Each virtual machine","External USB drives only","The monitor display","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "KVM (Kernel-based Virtual Machine) is a hypervisor built into:",
 "Windows","macOS","Linux","MS-DOS","C"),

("Virtualization & Architecture","Hypervisor Definition",
 "A hypervisor ensures that virtual machines are:",
 "All connected to each other insecurely",
 "Isolated from each other for security and stability",
 "Running only one at a time",
 "Sharing all passwords","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "The hypervisor sits between:",
 "The user and the keyboard",
 "The physical hardware and the virtual machines",
 "The printer and the monitor",
 "Two different buildings","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "Which is NOT a function of a hypervisor?",
 "Creating virtual machines","Allocating hardware resources to VMs","Manufacturing physical CPUs","Isolating virtual machines","C"),

# ── Role of Hypervisor in IaaS ──
("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "In IaaS, the hypervisor enables providers to:",
 "Ship physical servers to customers",
 "Partition physical servers into multiple virtual servers for different customers",
 "Only send emails",
 "Only store paper records","B"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "IaaS relies on hypervisors to deliver:",
 "Physical hardware to each customer",
 "Scalable and isolated virtual computing resources",
 "Only email services",
 "Only website hosting","B"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "When a user creates a VM in AWS EC2, a hypervisor:",
 "Sends a physical machine to the user",
 "Allocates virtual resources from a physical server",
 "Prints a receipt",
 "Does nothing","B"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "Multi-tenancy in IaaS is possible because hypervisors:",
 "Give everyone the same password",
 "Isolate each customer's virtual machines on shared hardware",
 "Merge all customer data together",
 "Require each customer to own hardware","B"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "The hypervisor in IaaS ensures that one customer's workload:",
 "Affects all other customers",
 "Does not impact other customers on the same physical host",
 "Crashes the entire data center",
 "Shares data with competitors","B"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "AWS uses a modified version of which hypervisor technology called Nitro?",
 "VMware ESXi","Xen/KVM-based","VirtualBox","Hyper-V","B"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "Azure uses which hypervisor for its IaaS offerings?",
 "VMware ESXi","Oracle VirtualBox","A customized version of Hyper-V","Parallels","C"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "The ability to rapidly create and destroy VMs in IaaS is enabled by:",
 "Manual hardware assembly",
 "Hypervisor automation and orchestration",
 "Paper order forms",
 "Physical server delivery","B"),

# ── Single Physical Resource Sharing ──
("Virtualization & Architecture","Single Physical Resource Sharing",
 "Resource pooling in cloud computing means:",
 "One resource per one user always",
 "Physical resources are shared among multiple users through virtualization",
 "No resources are available",
 "Each user has a separate building","B"),

("Virtualization & Architecture","Single Physical Resource Sharing",
 "A single physical server running 10 virtual machines demonstrates:",
 "Waste of resources","Efficient resource sharing through virtualization","Poor engineering","Data redundancy","B"),

("Virtualization & Architecture","Single Physical Resource Sharing",
 "CPU sharing among virtual machines is managed by:",
 "The user manually","The hypervisor","A paper schedule","The power supply","B"),

("Virtualization & Architecture","Single Physical Resource Sharing",
 "Memory overcommitment in virtualization allows:",
 "VMs to use more physical RAM than exists by using techniques like ballooning",
 "Unlimited free memory for all",
 "No memory usage at all",
 "Physical RAM to grow automatically","A"),

("Virtualization & Architecture","Single Physical Resource Sharing",
 "Storage from one SAN can be shared among multiple VMs using:",
 "Physical division with a saw",
 "Virtual disk allocation",
 "Paper records",
 "USB splitting","B"),

("Virtualization & Architecture","Single Physical Resource Sharing",
 "Network bandwidth on a physical NIC can be shared among VMs through:",
 "Cutting the cable into pieces",
 "Virtual network interfaces and traffic shaping",
 "Sending one packet at a time daily",
 "Paper letter routing","B"),

# ── Virtual Machine Isolation ──
("Virtualization & Architecture","Virtual Machine Isolation",
 "VM isolation ensures that:",
 "All VMs share the same memory space openly",
 "A crash in one VM does not affect other VMs on the same host",
 "All VMs must run the same operating system",
 "VMs have no security boundaries","B"),

("Virtualization & Architecture","Virtual Machine Isolation",
 "If one virtual machine gets a virus, isolation means:",
 "All VMs on the host get infected immediately",
 "Other VMs on the same host should remain unaffected",
 "The physical server explodes",
 "All data everywhere is lost","B"),

("Virtualization & Architecture","Virtual Machine Isolation",
 "VM isolation is critical for:",
 "Sharing passwords between VMs",
 "Multi-tenant cloud environments where different customers share hardware",
 "Running only one VM ever",
 "Avoiding all technology","B"),

("Virtualization & Architecture","Virtual Machine Isolation",
 "The hypervisor enforces isolation by:",
 "Giving all VMs admin access to the host",
 "Restricting each VM's access to only its allocated resources",
 "Turning off all security features",
 "Connecting all VM networks together without firewalls","B"),

("Virtualization & Architecture","Virtual Machine Isolation",
 "Memory isolation between VMs means:",
 "VMs can read each other's memory freely",
 "Each VM can only access its own allocated memory",
 "All memory is shared without protection",
 "No VM has any memory","B"),

("Virtualization & Architecture","Virtual Machine Isolation",
 "Network isolation between VMs can be achieved using:",
 "A single shared cable with no rules",
 "VLANs, virtual switches, and firewall rules",
 "No network equipment",
 "Only physical cables","B"),

# ── UTILITY & GRID COMPUTING ── Utility Computing Definition ──
("Utility & Grid Computing","Utility Computing Definition",
 "Utility computing provides computing resources as a:",
 "Free unlimited service",
 "Metered service similar to electricity or water",
 "One-time purchase",
 "Physical delivery product","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "The concept of utility computing is based on the idea of:",
 "Computing as a product you buy once",
 "Computing as a utility you pay for based on usage",
 "Free computing for all forever",
 "Computing without any electricity","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "Utility computing was one of the precursors to modern:",
 "Typewriters","Cloud computing","Fax machines","Postal services","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "In utility computing, resources such as storage and compute are provided:",
 "On a fixed annual contract only",
 "On demand and billed based on consumption",
 "For free with no limits",
 "Only through physical delivery","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "Utility computing aims to maximize:",
 "Hardware waste","Resource utilization and cost efficiency","Paper usage","Physical server count","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "Which term best describes the billing model of utility computing?",
 "Flat rate","Pay-per-use","Free tier only","Donation-based","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "Utility computing reduces the need for organizations to:",
 "Use any technology",
 "Maintain large in-house data centers for peak capacity",
 "Have any employees",
 "Connect to any network","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "John McCarthy's vision of computing as a public utility anticipated:",
 "The elimination of computers",
 "Modern cloud and utility computing",
 "The end of electricity",
 "Only mobile phones","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "Utility computing shares its billing philosophy with:",
 "Buying a car outright",
 "Paying a monthly electricity bill based on usage",
 "Getting free gasoline",
 "Owning a power plant","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "Elasticity in utility computing means:",
 "Physical servers can stretch",
 "Resources automatically scale based on demand",
 "Cables become flexible",
 "Hardware bends without breaking","B"),

# ── Pay-per-use Concept (Utility) ──
("Utility & Grid Computing","Pay-per-use Concept",
 "In pay-per-use utility computing, customers are charged for:",
 "Resources they never use",
 "Only the resources they actually consume",
 "All resources in the data center",
 "A random amount each month","B"),

("Utility & Grid Computing","Pay-per-use Concept",
 "Pay-per-use ensures that idle resources:",
 "Are still charged at full price to the user",
 "Are not charged until they are actively used",
 "Generate no revenue for the provider",
 "Must be physically returned","B"),

("Utility & Grid Computing","Pay-per-use Concept",
 "The pay-per-use model benefits organizations with:",
 "Constant unchanging workloads only",
 "Variable and unpredictable workloads",
 "No computing needs",
 "Only peak-time operations","B"),

("Utility & Grid Computing","Pay-per-use Concept",
 "Metering in utility computing is analogous to:",
 "A gas meter measuring consumption at home",
 "Unlimited free buffet",
 "A fixed salary",
 "A lottery system","A"),

("Utility & Grid Computing","Pay-per-use Concept",
 "Which is a benefit of pay-per-use for small businesses?",
 "They must buy expensive servers upfront",
 "They pay only for what they use, keeping costs low",
 "They get unlimited free services",
 "They cannot access any computing","B"),

# ── Grid Computing Definition ──
("Utility & Grid Computing","Grid Computing Definition",
 "Grid computing involves:",
 "A single powerful computer doing all work",
 "Multiple networked computers working together on large tasks",
 "Only one computer with no network",
 "A physical grid of solar panels","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "Grid computing distributes tasks across:",
 "A single processor",
 "Many geographically dispersed computers",
 "Only one building",
 "Paper-based systems","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "The primary goal of grid computing is to:",
 "Use only one computer for everything",
 "Harness unused computing power from multiple machines for complex problems",
 "Eliminate all computers",
 "Replace the internet","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "SETI@home was a famous example of grid computing that:",
 "Sold computers",
 "Used volunteer computers worldwide to analyze radio signals from space",
 "Built physical telescopes",
 "Replaced internet servers","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "Grid computing enables solving problems that are too large for:",
 "Any computer regardless of size",
 "A single computer or small cluster",
 "The entire internet",
 "All computers combined","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "Grid computing uses middleware to:",
 "Physically connect cables",
 "Coordinate tasks and manage resources across distributed computers",
 "Manufacture hardware",
 "Print documents","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "A computational grid is similar to:",
 "An electrical power grid distributing electricity",
 "A traffic jam",
 "A single wall outlet",
 "A paper grid notebook","A"),

("Utility & Grid Computing","Grid Computing Definition",
 "Grid computing was widely used in:",
 "Office word processing only",
 "Scientific research and large-scale data analysis",
 "Sending text messages",
 "Social media posts","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "Globus Toolkit is a well-known:",
 "Word processor",
 "Grid computing middleware",
 "Photo editor",
 "Email client","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "Grid computing can combine resources from:",
 "Only identical computers",
 "Different types of computers and operating systems",
 "Only Apple computers",
 "Only Windows computers","B"),

# ── Heterogeneous Resources ──
("Utility & Grid Computing","Heterogeneous Resources",
 "Heterogeneous resources in grid computing means:",
 "All computers are identical",
 "Computers with different hardware, OS, and configurations work together",
 "No computers are used",
 "Only brand-new computers are accepted","B"),

("Utility & Grid Computing","Heterogeneous Resources",
 "A grid computing system can include machines running:",
 "Only Windows","Only Linux","Different operating systems like Windows, Linux, and macOS","Only mainframes","C"),

("Utility & Grid Computing","Heterogeneous Resources",
 "Heterogeneity is a challenge in grid computing because:",
 "All systems are the same",
 "Software must be compatible across different hardware and OS environments",
 "No software is needed",
 "Only one computer type exists","B"),

("Utility & Grid Computing","Heterogeneous Resources",
 "Grid middleware handles heterogeneity by:",
 "Requiring all computers to be identical",
 "Providing a common interface that abstracts hardware differences",
 "Throwing away non-matching computers",
 "Using only one computer","B"),

("Utility & Grid Computing","Heterogeneous Resources",
 "A computational grid with Linux servers, Windows workstations, and macOS laptops is an example of:",
 "A homogeneous system","A heterogeneous grid","A local area network only","A single computer","B"),

# ── Geographically Dispersed Systems ──
("Utility & Grid Computing","Geographically Dispersed Systems",
 "Grid computing nodes can be located in:",
 "The same room only",
 "Different cities, countries, or continents",
 "A single building only",
 "One data center only","B"),

("Utility & Grid Computing","Geographically Dispersed Systems",
 "The geographic distribution of grid nodes is connected via:",
 "Physical cables only in one building",
 "Wide area networks and the internet",
 "Paper mail",
 "Radio waves only","B"),

("Utility & Grid Computing","Geographically Dispersed Systems",
 "A challenge of geographically dispersed grids is:",
 "All nodes being in the same place",
 "Network latency between distant nodes",
 "Too many nodes being too close",
 "Identical time zones","B"),

("Utility & Grid Computing","Geographically Dispersed Systems",
 "International research projects use geographically dispersed grids to:",
 "Avoid using computers",
 "Pool computing power from institutions worldwide",
 "Send physical samples through the mail",
 "Only communicate via fax","B"),

("Utility & Grid Computing","Geographically Dispersed Systems",
 "The European Grid Infrastructure connects:",
 "Only European businesses",
 "Research institutions across Europe and beyond",
 "Only American universities",
 "No institutions at all","B"),

# ── Difference: Grid vs Cloud ──
("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Grid computing focuses on:",
 "On-demand scalable services",
 "Distributed problem-solving across many heterogeneous machines",
 "Selling ready-made software",
 "Only email delivery","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Cloud computing focuses on:",
 "Only scientific research",
 "Delivering on-demand IT services over the internet",
 "Only grid-based calculations",
 "Only hardware manufacturing","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Grid computing is typically used for:",
 "Consumer web applications",
 "Large-scale scientific and research computations",
 "Social media browsing",
 "Online shopping only","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Cloud computing is commonly used for:",
 "Only particle physics research",
 "Business applications, storage, web hosting, and general-purpose IT",
 "Only weather prediction",
 "Only space exploration","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "In grid computing, resources are typically:",
 "Owned by a single provider",
 "Contributed by multiple independent organizations",
 "Purchased from a single vendor",
 "Not used at all","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "In cloud computing, resources are typically owned and managed by:",
 "Multiple independent contributors",
 "A single cloud service provider",
 "No one at all",
 "The end user exclusively","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Grid computing predates cloud computing and was prominent in the:",
 "1960s","1990s and early 2000s","2020s","2030s","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Cloud computing became mainstream in the:",
 "1970s","1990s","Late 2000s and 2010s","1950s","C"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Cloud provides virtualized resources while grid typically combines:",
 "Virtual machines only",
 "Physical distributed machines into a unified computing resource",
 "Only storage",
 "Only networking","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Which is more consumer-friendly and commercially available?",
 "Grid computing","Cloud computing","Neither","Both equally","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "SLA (Service Level Agreements) are a standard part of:",
 "Grid computing mainly","Cloud computing","Postal services","Neither","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Scalability is more seamless and automatic in:",
 "Grid computing","Cloud computing","Both equally","Neither","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Grid computing resources are often:",
 "Available 24/7 with guaranteed uptime",
 "Voluntarily contributed and availability may vary",
 "Always 100% reliable",
 "Free of any latency","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Cloud computing provides guaranteed uptime through:",
 "Volunteer computers",
 "SLAs backed by redundant professional infrastructure",
 "Hoping for the best",
 "Single points of failure","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Multi-tenancy is a core feature of:",
 "Grid computing","Cloud computing","Neither","Paper-based systems","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Which statement is TRUE?",
 "Cloud replaced grid computing entirely",
 "Grid computing concepts influenced cloud computing's development",
 "Grid and cloud are exactly the same thing",
 "Neither grid nor cloud uses the internet","B"),
]
