# Section 1 Questions 601-800: I/O Devices, Keyboard, Hardware Basics, Types of Computers
# Format: (topic, subtopic, question, optA, optB, optC, optD, answer)

def get_questions():
    return [
# ── INPUT/OUTPUT DEVICES ── Laser Printer ──
("Input/Output Devices","Laser Printer",
 "A laser printer uses which technology to produce prints?",
 "Ink spraying","Laser beam and toner","Impact ribbons","Thermal wax","B"),

("Input/Output Devices","Laser Printer",
 "Laser printers are known for producing:",
 "Low-quality blurry prints",
 "High-quality, sharp text and graphics",
 "Only colored prints",
 "Only handwritten text","B"),

("Input/Output Devices","Laser Printer",
 "The main consumable in a laser printer is:",
 "Ink cartridge","Toner cartridge","Ribbon","Paper only","B"),

("Input/Output Devices","Laser Printer",
 "Laser printers are typically faster than:",
 "Other laser printers","Inkjet printers","Nothing, they are the slowest","Network switches","B"),

("Input/Output Devices","Laser Printer",
 "A laser printer uses a drum to:",
 "Store music",
 "Transfer toner to paper using electrostatic charge",
 "Spin the paper in circles",
 "Generate electricity","B"),

("Input/Output Devices","Laser Printer",
 "Laser printers are ideal for:",
 "Only printing photos",
 "High-volume office printing with fast speeds",
 "Only printing envelopes",
 "Only printing on fabric","B"),

("Input/Output Devices","Laser Printer",
 "The resolution of laser printers is measured in:",
 "PPM","DPI (Dots Per Inch)","RPM","GHz","B"),

("Input/Output Devices","Laser Printer",
 "A typical office laser printer resolution is:",
 "72 DPI","600 to 1200 DPI","10 DPI","1 DPI","B"),

("Input/Output Devices","Laser Printer",
 "Laser printers produce less noise compared to:",
 "All devices","Impact printers like dot matrix","Other laser printers","No printers","B"),

("Input/Output Devices","Laser Printer",
 "Color laser printers use how many toner cartridges?",
 "One","Four (Cyan, Magenta, Yellow, Black)","Two","Ten","B"),

("Input/Output Devices","Laser Printer",
 "The process inside a laser printer includes:",
 "Only heating paper",
 "Charging, exposing, developing, transferring, and fusing",
 "Only cutting paper",
 "Only folding paper","B"),

("Input/Output Devices","Laser Printer",
 "A fuser unit in a laser printer:",
 "Cools down the paper",
 "Heats and presses toner onto the paper to make it permanent",
 "Cuts the paper",
 "Adds water to the paper","B"),

("Input/Output Devices","Laser Printer",
 "Cost per page for laser printers is typically:",
 "Higher than inkjet printers",
 "Lower than inkjet printers for text printing",
 "The same as handwriting",
 "Infinite","B"),

# ── Printer Speed (PPM) ──
("Input/Output Devices","Printer Speed (PPM)",
 "PPM stands for:",
 "Pages Per Minute","Pixels Per Monitor","Prints Per Month","Points Per Margin","A"),

("Input/Output Devices","Printer Speed (PPM)",
 "A printer rated at 30 PPM can print approximately:",
 "30 pages per hour","30 pages per minute","30 pages per day","30 pages per year","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "Higher PPM rating indicates:",
 "Slower printing","Faster printing speed","Better color quality","Larger paper size","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "Office laser printers typically have PPM ratings of:",
 "1-2 PPM","20-50 PPM","500+ PPM","0.5 PPM","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "PPM ratings may vary between monochrome and color printing because:",
 "Color printing is always faster",
 "Color printing requires processing more data (CMYK) and is usually slower",
 "Both are always the same speed",
 "Monochrome printing requires more ink","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "A home inkjet printer typically has a PPM of:",
 "100+ PPM","5-15 PPM","500 PPM","0.1 PPM","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "Industrial production printers can have PPM ratings of:",
 "Less than 1 PPM",
 "Over 100 PPM or even thousands per hour",
 "Exactly 2 PPM always",
 "0 PPM","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "PPM is an important specification when choosing a printer for:",
 "Home decoration purposes",
 "High-volume office environments where speed matters",
 "Painting artwork",
 "Cooking recipes","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "First Page Out Time is related to PPM and measures:",
 "How long before the printer is discarded",
 "Time taken to produce the first printed page after sending a job",
 "How long paper lasts in storage",
 "The time to install a printer","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "Duplex printing at a given PPM:",
 "Doubles the speed",
 "May reduce effective PPM since both sides are printed",
 "Has no effect on speed",
 "Triples the speed","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "Network printers serving many users need higher PPM to:",
 "Save electricity",
 "Handle multiple print jobs efficiently",
 "Look more expensive",
 "Reduce paper jams","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "PPM is measured for printing at:",
 "Maximum resolution with full color",
 "Standard or draft quality for consistent benchmarking",
 "The smallest possible paper",
 "With no paper loaded","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "A label printer typically has lower PPM because:",
 "It prints on larger paper",
 "Labels are smaller and require precise alignment per print",
 "It uses no ink",
 "It prints faster than office printers","B"),

# ── DPI vs PPM ──
("Input/Output Devices","DPI vs PPM",
 "DPI measures print:",
 "Speed","Quality (resolution)","Cost","Weight","B"),

("Input/Output Devices","DPI vs PPM",
 "PPM measures print:",
 "Quality","Speed","Color depth","Paper size","B"),

("Input/Output Devices","DPI vs PPM",
 "A printer with 1200 DPI and 30 PPM has:",
 "High resolution and high speed",
 "Low resolution and low speed",
 "No printing capability",
 "Only scanning capability","A"),

("Input/Output Devices","DPI vs PPM",
 "For photo printing, which specification matters more?",
 "PPM","DPI","Both are irrelevant","Paper weight only","B"),

("Input/Output Devices","DPI vs PPM",
 "For bulk office document printing, which specification matters more?",
 "DPI mainly","PPM mainly","Neither","The printer's color","B"),

("Input/Output Devices","DPI vs PPM",
 "Higher DPI means:",
 "Faster output",
 "More dots per inch, resulting in sharper and more detailed prints",
 "Fewer pages printed",
 "Louder printing","B"),

("Input/Output Devices","DPI vs PPM",
 "A printer advertising 600 DPI and 40 PPM is suited for:",
 "Very slow photo printing only",
 "Fast office printing with good text quality",
 "No practical use",
 "Only envelope printing","B"),

("Input/Output Devices","DPI vs PPM",
 "Increasing DPI generally:",
 "Speeds up printing",
 "May slow down printing as more detail needs to be rendered",
 "Has no effect on anything",
 "Reduces print quality","B"),

("Input/Output Devices","DPI vs PPM",
 "A 300 DPI print is suitable for:",
 "Billboard advertising only",
 "Standard text documents and basic graphics",
 "Microscopic analysis",
 "No practical use","B"),

("Input/Output Devices","DPI vs PPM",
 "Printers with very high DPI (2400+) are typically used for:",
 "Draft printing",
 "Professional photo and graphic design printing",
 "Printing blank pages",
 "Text-only printing","B"),

("Input/Output Devices","DPI vs PPM",
 "ISO standards for measuring PPM ensure:",
 "All printers claim the same speed",
 "Consistent and comparable speed ratings across different printer brands",
 "No standards exist",
 "Only one brand can measure PPM","B"),

("Input/Output Devices","DPI vs PPM",
 "An inkjet printer with 4800 DPI but only 8 PPM is best for:",
 "High-volume office printing",
 "High-quality photo printing at home",
 "Industrial printing",
 "No printing at all","B"),

("Input/Output Devices","DPI vs PPM",
 "DPI is relevant for both printers and:",
 "Keyboards","Scanners","Power supplies","Speakers","B"),

("Input/Output Devices","DPI vs PPM",
 "Scanner DPI determines the:",
 "Speed of scanning",
 "Detail and quality of the scanned image",
 "Color of the scanner",
 "Size of the scanner","B"),

# ── KEYBOARD & HARDWARE ── ESC Key ──
("Keyboard & Hardware","ESC Key",
 "The ESC key on a keyboard stands for:",
 "Essential System Control","Escape","External System Command","Electronic Signal Controller","B"),

("Keyboard & Hardware","ESC Key",
 "The ESC key is typically used to:",
 "Type letters",
 "Cancel or close a current operation or dialog box",
 "Turn off the computer",
 "Increase volume","B"),

("Keyboard & Hardware","ESC Key",
 "Pressing ESC while viewing a full-screen video usually:",
 "Deletes the video","Exits full-screen mode","Increases brightness","Mutes audio","B"),

("Keyboard & Hardware","ESC Key",
 "The ESC key is located at the:",
 "Bottom right of the keyboard",
 "Top left corner of the keyboard",
 "Center of the keyboard",
 "On the mouse","B"),

("Keyboard & Hardware","ESC Key",
 "In many dialog boxes, pressing ESC is equivalent to clicking:",
 "OK","Cancel","Save","Print","B"),

("Keyboard & Hardware","ESC Key",
 "In web browsers, pressing ESC can:",
 "Delete all bookmarks",
 "Stop a page from loading",
 "Open a new tab",
 "Print the page","B"),

("Keyboard & Hardware","ESC Key",
 "The ESC key is part of which section of the keyboard?",
 "Numeric keypad","Function keys area","Alphabetic section","Arrow keys section","B"),

("Keyboard & Hardware","ESC Key",
 "In gaming, the ESC key is often used to:",
 "Jump","Open the pause or menu screen","Attack","Move forward","B"),

("Keyboard & Hardware","ESC Key",
 "When filling a form online, pressing ESC may:",
 "Submit the form",
 "Close a dropdown or dismiss a popup",
 "Delete all typed text permanently",
 "Log you out of the system","B"),

("Keyboard & Hardware","ESC Key",
 "In Microsoft Excel, pressing ESC while editing a cell:",
 "Saves the cell content",
 "Cancels the edit and restores the original value",
 "Deletes the entire spreadsheet",
 "Prints the worksheet","B"),

# ── Enter Key ──
("Keyboard & Hardware","Enter Key",
 "The Enter key is also known as the:",
 "Escape key","Return key","Delete key","Backspace key","B"),

("Keyboard & Hardware","Enter Key",
 "The Enter key is primarily used to:",
 "Delete text",
 "Confirm a command or move to a new line",
 "Turn off the monitor",
 "Adjust brightness","B"),

("Keyboard & Hardware","Enter Key",
 "In a word processor, pressing Enter creates a:",
 "Bold text","New paragraph or line break","Table","Header","B"),

("Keyboard & Hardware","Enter Key",
 "In a web browser address bar, pressing Enter:",
 "Deletes the URL",
 "Navigates to the typed URL",
 "Closes the browser",
 "Opens settings","B"),

("Keyboard & Hardware","Enter Key",
 "When typing in a search engine, pressing Enter:",
 "Clears the search box",
 "Executes the search query",
 "Closes the search engine",
 "Opens a new tab","B"),

("Keyboard & Hardware","Enter Key",
 "In a command-line interface, pressing Enter:",
 "Cancels the command",
 "Executes the typed command",
 "Opens a GUI window",
 "Shuts down the computer","B"),

("Keyboard & Hardware","Enter Key",
 "Most keyboards have Enter keys on:",
 "Only the left side",
 "The main keyboard area and the numeric keypad",
 "Only the top row",
 "Only the function key row","B"),

("Keyboard & Hardware","Enter Key",
 "In dialog boxes, pressing Enter often activates the:",
 "Cancel button",
 "Default or highlighted button (usually OK)",
 "Close window button",
 "Print button","B"),

("Keyboard & Hardware","Enter Key",
 "In spreadsheets, pressing Enter after typing in a cell:",
 "Deletes the cell",
 "Confirms the entry and moves to the next cell",
 "Formats the cell as bold",
 "Merges cells together","B"),

("Keyboard & Hardware","Enter Key",
 "The Enter key was originally called Return on:",
 "IBM keyboards","Apple Macintosh keyboards","No keyboards","Only gaming keyboards","B"),

# ── Delete Key ──
("Keyboard & Hardware","Delete Key",
 "The Delete key removes characters:",
 "To the left of the cursor",
 "To the right of the cursor (or the selected item)",
 "Above the cursor",
 "Below the cursor","B"),

("Keyboard & Hardware","Delete Key",
 "The Delete key differs from Backspace in that:",
 "Both do the same thing",
 "Delete removes characters to the right; Backspace removes to the left",
 "Delete types characters; Backspace removes them",
 "Delete increases font size","B"),

("Keyboard & Hardware","Delete Key",
 "In file management, pressing Delete on a selected file:",
 "Opens the file",
 "Moves the file to the Recycle Bin or Trash",
 "Renames the file",
 "Copies the file","B"),

("Keyboard & Hardware","Delete Key",
 "Shift + Delete on Windows permanently deletes a file:",
 "Into the Recycle Bin",
 "Without sending it to the Recycle Bin",
 "To a backup folder",
 "To the desktop","B"),

("Keyboard & Hardware","Delete Key",
 "In word processors, the Delete key removes:",
 "The entire document",
 "The character or selected text at or after the cursor position",
 "Only images",
 "Only headers","B"),

("Keyboard & Hardware","Delete Key",
 "Ctrl + Alt + Delete on Windows opens:",
 "A game",
 "Task Manager or a security options screen",
 "The calculator",
 "Microsoft Paint","B"),

("Keyboard & Hardware","Delete Key",
 "On many laptop keyboards, the Delete key may require using the:",
 "Mouse only","Fn key combination","Touchscreen","External keyboard","B"),

("Keyboard & Hardware","Delete Key",
 "In email applications, the Delete key:",
 "Sends the email",
 "Moves the selected email to the Trash folder",
 "Forwards the email",
 "Composes a new email","B"),

("Keyboard & Hardware","Delete Key",
 "The Delete key is located near which area of a standard keyboard?",
 "The spacebar","Above the arrow keys (navigation cluster)","The numeric keypad only","The function keys only","B"),

("Keyboard & Hardware","Delete Key",
 "In spreadsheet software, pressing Delete on a selected cell:",
 "Deletes the entire column",
 "Clears the cell contents",
 "Saves the spreadsheet",
 "Prints the cell","B"),

# ── Insert Key ──
("Keyboard & Hardware","Insert Key",
 "The Insert key toggles between:",
 "Bold and italic",
 "Insert mode and overtype mode",
 "Upper and lower case",
 "English and French","B"),

("Keyboard & Hardware","Insert Key",
 "In insert mode, typing adds new characters:",
 "By replacing existing characters",
 "Without replacing existing text",
 "By deleting the entire line",
 "At the end of the document only","B"),

("Keyboard & Hardware","Insert Key",
 "In overtype mode, typing:",
 "Adds characters before existing text",
 "Replaces existing characters with the newly typed ones",
 "Deletes the entire paragraph",
 "Only changes font size","B"),

("Keyboard & Hardware","Insert Key",
 "The Insert key is abbreviated as:",
 "DEL","INS","ESC","TAB","B"),

("Keyboard & Hardware","Insert Key",
 "Shift + Insert is a keyboard shortcut for:",
 "Copy","Paste","Cut","Undo","B"),

("Keyboard & Hardware","Insert Key",
 "Ctrl + Insert is a keyboard shortcut for:",
 "Paste","Copy","Cut","Delete","B"),

("Keyboard & Hardware","Insert Key",
 "The Insert key is located in the:",
 "Bottom left of the keyboard",
 "Navigation key cluster between the main keys and numeric keypad",
 "Top left corner",
 "On the mouse","B"),

("Keyboard & Hardware","Insert Key",
 "In many modern applications, the Insert key is:",
 "The most used key",
 "Rarely used and sometimes disabled by default",
 "Used for power management",
 "Used to adjust screen brightness","B"),

("Keyboard & Hardware","Insert Key",
 "In older DOS-based text editors, the Insert key was essential for:",
 "Playing games",
 "Switching between text entry modes",
 "Changing screen resolution",
 "Connecting to the internet","B"),

("Keyboard & Hardware","Insert Key",
 "Some modern keyboards omit the Insert key to:",
 "Add more letter keys",
 "Save space in compact keyboard designs",
 "Reduce cost by removing all keys",
 "Make the keyboard heavier","B"),

# ── COMPUTER HARDWARE BASICS ── Semiconductor Definition ──
("Computer Hardware Basics","Semiconductor Definition",
 "A semiconductor is a material with electrical conductivity between:",
 "Two metals",
 "A conductor and an insulator",
 "Two insulators",
 "A liquid and a gas","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "The most commonly used semiconductor material is:",
 "Copper","Silicon","Gold","Iron","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Semiconductors are the basis of:",
 "Light bulbs only","Modern electronic components like transistors and chips","Wooden furniture","Paper production","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Doping a semiconductor means:",
 "Painting it","Adding impurities to change its electrical properties","Heating it to high temperatures only","Cooling it to below zero","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "N-type semiconductor is created by adding impurities that provide extra:",
 "Protons","Electrons","Neutrons","Photons","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "P-type semiconductor is created by adding impurities that create:",
 "Extra electrons","Holes (absence of electrons)","Extra protons","Extra neutrons","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "A transistor is made from:",
 "Only conductors","Semiconductor materials","Only insulators","Only plastics","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Semiconductors operate best at:",
 "Absolute zero temperature only",
 "Room temperature and controlled conditions",
 "Boiling temperature only",
 "Extreme cold only","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Silicon Valley gets its name from:",
 "A valley made of silicon rocks",
 "The prevalence of semiconductor (silicon-based) technology companies",
 "A type of food",
 "A historical mining operation","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Germanium was used as a semiconductor before:",
 "It was replaced by gold",
 "Silicon became the dominant material",
 "It was banned worldwide",
 "Copper replaced it","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "LEDs (Light Emitting Diodes) are made from:",
 "Pure metals","Semiconductor materials","Glass only","Plastic only","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Integrated circuits (ICs) contain thousands to billions of:",
 "Wires","Transistors made from semiconductors","Light bulbs","Batteries","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "The semiconductor industry is critical for manufacturing:",
 "Only automobiles",
 "CPUs, memory chips, sensors, and most electronic devices",
 "Only furniture",
 "Only clothing","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "A diode is a semiconductor device that allows current to flow in:",
 "Any direction equally","Primarily one direction","No direction at all","Only when heated","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Photovoltaic cells (solar cells) use semiconductors to convert:",
 "Sound to electricity","Light to electricity","Heat to sound","Wind to light","B"),

# ── Chip Manufacturing Concept ──
("Computer Hardware Basics","Chip Manufacturing Concept",
 "Computer chips are manufactured on thin wafers of:",
 "Copper","Silicon","Gold","Aluminum","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "The process of creating patterns on a silicon wafer is called:",
 "Printing","Photolithography","Painting","Welding","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "A fabrication plant for chip manufacturing is commonly called a:",
 "Workshop","Fab","Studio","Kitchen","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "Chip manufacturing occurs in:",
 "Open fields",
 "Cleanrooms with controlled particle-free environments",
 "Regular offices",
 "Outdoor factories","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "The size of transistors on modern chips is measured in:",
 "Meters","Nanometers","Kilometers","Centimeters","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "Smaller transistor sizes allow chips to be:",
 "Slower and larger",
 "Faster, more power-efficient, and contain more transistors",
 "Less useful",
 "Heavier","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "TSMC (Taiwan Semiconductor Manufacturing Company) is the world's largest:",
 "Car manufacturer","Contract chip manufacturer","Furniture company","Food processor","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "Intel and AMD are major designers of:",
 "Clothing","Computer processors (CPUs and GPUs)","Musical instruments","Kitchen appliances","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "Moore's Law predicts that the number of transistors on a chip:",
 "Stays the same forever","Roughly doubles every two years","Halves every year","Triples every month","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "EUV (Extreme Ultraviolet) lithography is used for manufacturing chips at:",
 "Large scale factories for cars",
 "Very small nanometer nodes (7nm, 5nm, 3nm)",
 "Large building construction",
 "Food packaging","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "A single silicon wafer can produce:",
 "One chip only","Hundreds to thousands of chips","No chips at all","Only ten chips","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "After fabrication, chips undergo testing to:",
 "Make them look pretty",
 "Identify defective units and ensure quality",
 "Add more transistors",
 "Change their color","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "Packaging of a chip involves:",
 "Wrapping it in paper",
 "Enclosing the silicon die in a protective casing with electrical connections",
 "Destroying it",
 "Painting it","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "The chip supply chain involves:",
 "Only one company",
 "Design houses, foundries, packaging firms, and testing facilities",
 "Only retail stores",
 "No companies at all","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "ARM, Qualcomm, and Apple design chips but often have them manufactured by:",
 "Their own factories only","Foundries like TSMC and Samsung","Home users","Retail stores","B"),

# ── TYPES OF COMPUTERS ── Analog Computer ──
("Types of Computers","Analog Computer",
 "An analog computer processes:",
 "Only binary digital data",
 "Continuous data such as temperature, pressure, or voltage",
 "Only text files",
 "Only images","B"),

("Types of Computers","Analog Computer",
 "An example of an analog computing device is a:",
 "Laptop","Speedometer in a car","Smartphone","Desktop PC","B"),

("Types of Computers","Analog Computer",
 "Analog computers represent data using:",
 "Discrete binary digits (0 and 1)",
 "Continuously varying physical quantities",
 "Only text characters",
 "Only colored pixels","B"),

("Types of Computers","Analog Computer",
 "A thermometer that shows temperature on a sliding scale is an example of:",
 "Digital device","Analog device","Hybrid device","No computing device","B"),

("Types of Computers","Analog Computer",
 "Analog computers were widely used for:",
 "Social media browsing",
 "Scientific and engineering simulations before digital computers",
 "Only gaming",
 "Only word processing","B"),

("Types of Computers","Analog Computer",
 "A slide rule is an example of a simple:",
 "Digital computer","Analog computing device","Hybrid computer","Printer","B"),

("Types of Computers","Analog Computer",
 "Analog computers are less accurate than digital computers because:",
 "They use more bits",
 "Physical measurements are subject to noise and limited precision",
 "They are faster",
 "They use binary code","B"),

("Types of Computers","Analog Computer",
 "An analog clock with moving hands is an example of:",
 "Digital display","Analog representation of time","Binary computing","Hybrid computing","B"),

("Types of Computers","Analog Computer",
 "Analog computers work best with:",
 "Discrete integer values only",
 "Real-world physical phenomena that change continuously",
 "Boolean logic only",
 "Text processing only","B"),

("Types of Computers","Analog Computer",
 "The output of an analog computer is typically:",
 "A printed report",
 "A continuous graph, dial reading, or physical measurement",
 "A digital display only",
 "A binary code sequence","B"),

("Types of Computers","Analog Computer",
 "Operational amplifiers are key components in analog computers used for:",
 "Displaying text",
 "Performing mathematical operations on continuous signals",
 "Storing digital files",
 "Printing documents","B"),

("Types of Computers","Analog Computer",
 "Analog computers have been largely replaced by digital computers because:",
 "Analog is more accurate",
 "Digital computers offer higher precision, flexibility, and programmability",
 "Digital computers are always cheaper",
 "Analog computers are too small","B"),

("Types of Computers","Analog Computer",
 "A fuel gauge in a car is an example of:",
 "Digital computing","Analog measurement","Hybrid computing","Binary system","B"),

# ── Digital Computer ──
("Types of Computers","Digital Computer",
 "A digital computer processes data in the form of:",
 "Continuous signals","Discrete binary digits (0 and 1)","Analog waves","Physical measurements only","B"),

("Types of Computers","Digital Computer",
 "Which of the following is a digital computer?",
 "A mercury thermometer","A laptop computer","A vinyl record player","A sundial","B"),

("Types of Computers","Digital Computer",
 "Digital computers are more accurate than analog computers because:",
 "They are more physical",
 "They use precise binary representation and are not affected by signal noise",
 "They are slower",
 "They cannot process data","B"),

("Types of Computers","Digital Computer",
 "The binary system used by digital computers has a base of:",
 "8","10","2","16","C"),

("Types of Computers","Digital Computer",
 "Digital computers can be programmed to:",
 "Only one specific task",
 "Perform a vast variety of tasks through software",
 "Nothing at all",
 "Only calculate numbers","B"),

("Types of Computers","Digital Computer",
 "Examples of digital computers include:",
 "Only mainframes","Desktops, laptops, tablets, and smartphones","Only calculators","Only watches","B"),

("Types of Computers","Digital Computer",
 "Digital computers store data in:",
 "Analog signals","Binary form (bits and bytes)","Continuous waveforms","Physical samples","B"),

("Types of Computers","Digital Computer",
 "A bit in digital computing is:",
 "A small tool",
 "The smallest unit of data, either 0 or 1",
 "A type of cable",
 "A color code","B"),

("Types of Computers","Digital Computer",
 "A byte consists of:",
 "4 bits","8 bits","16 bits","1 bit","B"),

("Types of Computers","Digital Computer",
 "Digital computers execute instructions through:",
 "Analog signal processing",
 "A CPU that processes binary instructions",
 "Paper tape reading only",
 "Voice commands only","B"),

("Types of Computers","Digital Computer",
 "Digital computers are classified by size as:",
 "Only supercomputers",
 "Microcomputers, minicomputers, mainframes, and supercomputers",
 "Only laptops",
 "Only smartphones","B"),

("Types of Computers","Digital Computer",
 "The versatility of digital computers comes from their ability to:",
 "Process only one data type",
 "Run different software programs for different tasks",
 "Only display video",
 "Only play music","B"),

("Types of Computers","Digital Computer",
 "ENIAC was one of the first general-purpose:",
 "Analog computers","Electronic digital computers","Hybrid computers","Quantum computers","B"),

# ── Hybrid Computer ──
("Types of Computers","Hybrid Computer",
 "A hybrid computer combines features of:",
 "Only digital computers",
 "Both analog and digital computers",
 "Only analog computers",
 "Only quantum computers","B"),

("Types of Computers","Hybrid Computer",
 "Hybrid computers are used when:",
 "Only digital processing is needed",
 "Both continuous analog input and precise digital processing are required",
 "No computing is needed",
 "Only text processing is required","B"),

("Types of Computers","Hybrid Computer",
 "In a hybrid computer, the analog component typically:",
 "Stores files permanently",
 "Accepts real-world continuous input like temperature or pressure",
 "Only displays graphics",
 "Only prints reports","B"),

("Types of Computers","Hybrid Computer",
 "In a hybrid computer, the digital component typically:",
 "Measures physical quantities",
 "Processes the analog input with high precision and provides digital output",
 "Only plays music",
 "Only takes photographs","B"),

("Types of Computers","Hybrid Computer",
 "An ECG (Electrocardiogram) machine is an example of a:",
 "Pure digital computer","Pure analog computer","Hybrid computer","Quantum computer","C"),

("Types of Computers","Hybrid Computer",
 "A hybrid computer in a hospital might measure a patient's vital signs (analog) and:",
 "Ignore the data",
 "Process them digitally for display and analysis",
 "Only print them on paper",
 "Only send them via fax","B"),

("Types of Computers","Hybrid Computer",
 "Petrol pump systems use hybrid computing to:",
 "Only display advertisements",
 "Measure fuel flow (analog) and calculate cost digitally",
 "Only play music",
 "Only accept cash payments","B"),

("Types of Computers","Hybrid Computer",
 "Hybrid computers offer the advantage of:",
 "Neither speed nor accuracy",
 "Speed of analog processing combined with accuracy of digital processing",
 "Only analog disadvantages",
 "Only digital disadvantages","B"),

("Types of Computers","Hybrid Computer",
 "Scientific research often uses hybrid computers for:",
 "Only browsing the internet",
 "Processing experimental analog data with digital precision",
 "Only sending emails",
 "Only playing video games","B"),

# ── Hybrid Computer Use-cases ──
("Types of Computers","Hybrid Computer Use-cases",
 "In weather forecasting, hybrid computers can:",
 "Only display forecasts",
 "Process continuous atmospheric data and compute digital weather models",
 "Only print weather maps",
 "Only send weather alerts","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Defense systems may use hybrid computers for:",
 "Only paperwork",
 "Real-time radar signal processing (analog) with digital command and control",
 "Only email communication",
 "Only administrative tasks","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "In the oil industry, hybrid computers can:",
 "Only count barrels",
 "Monitor continuous flow measurements and compute extraction rates digitally",
 "Only print invoices",
 "Only manage employee schedules","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "CT scan machines in hospitals use hybrid computing to:",
 "Only store patient names",
 "Convert continuous X-ray signals into digital images for diagnosis",
 "Only print appointment schedules",
 "Only manage billing","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Aircraft flight simulators may use hybrid computers to:",
 "Only display menus",
 "Process continuous sensor inputs and compute digital flight dynamics in real time",
 "Only record audio",
 "Only manage ticketing","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Industrial process control systems are hybrid because they:",
 "Only use digital inputs",
 "Monitor analog sensors (temperature, pressure) and control processes digitally",
 "Only print reports",
 "Have no computing function","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Automobile engine management systems are hybrid because they:",
 "Only play radio",
 "Read analog sensor data and digitally adjust fuel injection and ignition",
 "Only display speed",
 "Only control windows","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Robotic systems often use hybrid computing for:",
 "Only appearance",
 "Processing sensor data (analog) and executing precise digital control algorithms",
 "Only decorative purposes",
 "Only communications","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "An ultrasound machine is a hybrid system because it:",
 "Only stores appointment data",
 "Captures analog sound wave reflections and processes them into digital images",
 "Only prints labels",
 "Only plays music during procedures","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Analog-to-Digital Converters (ADC) are essential components in hybrid computers because they:",
 "Delete analog signals",
 "Convert continuous analog signals into discrete digital values for processing",
 "Only amplify sounds",
 "Only measure weight","B"),
]
