# Section 1 Questions 801-1000: Storage & Processing, Programming Translators
# Format: (topic, subtopic, question, optA, optB, optC, optD, answer)

def get_questions():
    return [
# ── STORAGE & PROCESSING ── Sequential Access Devices ──
("Storage & Processing","Sequential Access Devices",
 "Sequential access means data is read:",
 "In any random order instantly",
 "In a fixed linear order from beginning to end",
 "Backwards only",
 "In circular patterns","B"),

("Storage & Processing","Sequential Access Devices",
 "Which of the following is a sequential access storage device?",
 "SSD","Hard disk drive","Magnetic tape","USB flash drive","C"),

("Storage & Processing","Sequential Access Devices",
 "Reading data from a sequential access device is slower because:",
 "All data is available instantly",
 "You must pass through preceding data to reach the desired data",
 "It has no storage medium",
 "It uses no electricity","B"),

("Storage & Processing","Sequential Access Devices",
 "Sequential access is analogous to:",
 "Using a table of contents to jump to a chapter",
 "Fast-forwarding a VHS tape to find a scene",
 "Using a search engine",
 "Clicking a bookmark","B"),

("Storage & Processing","Sequential Access Devices",
 "Sequential access is the opposite of:",
 "No access","Random access (direct access)","Physical access","Remote access","B"),

("Storage & Processing","Sequential Access Devices",
 "Which data structure uses sequential access by nature?",
 "Array with index","Linked list traversal","Hash table","Binary search tree","B"),

("Storage & Processing","Sequential Access Devices",
 "Audio cassette tapes use:",
 "Random access","Sequential access","No access method","Parallel access","B"),

("Storage & Processing","Sequential Access Devices",
 "VHS video tapes use:",
 "Random access like a DVD","Sequential access","Cloud access","Wireless access","B"),

("Storage & Processing","Sequential Access Devices",
 "Sequential access is efficient for:",
 "Randomly retrieving individual records",
 "Processing all data in order (batch processing, backups)",
 "Real-time database queries",
 "Interactive gaming","B"),

("Storage & Processing","Sequential Access Devices",
 "A program that reads an entire file from start to finish uses:",
 "Random access pattern","Sequential access pattern","No access pattern","Cloud access only","B"),

("Storage & Processing","Sequential Access Devices",
 "Seeking a specific song on a cassette tape requires:",
 "Instant playback","Winding or fast-forwarding through the tape sequentially","No action","Pressing a search button","B"),

("Storage & Processing","Sequential Access Devices",
 "Modern SSDs do NOT use sequential access because:",
 "They have no storage",
 "They use electronic flash memory allowing instant random access",
 "They use tape technology",
 "They have no speed","B"),

("Storage & Processing","Sequential Access Devices",
 "Batch processing systems traditionally used sequential access for:",
 "Real-time responses",
 "Processing large volumes of sorted records efficiently",
 "Interactive user interfaces",
 "Video streaming","B"),

("Storage & Processing","Sequential Access Devices",
 "The access time for sequential devices depends on:",
 "Only the device's color",
 "The position of the desired data relative to the current read position",
 "Only the room temperature",
 "Only the time of day","B"),

("Storage & Processing","Sequential Access Devices",
 "Paper tape, an early storage medium, used:",
 "Random access","Sequential access","Cloud access","Digital access only","B"),

# ── Magnetic Tape Usage ──
("Storage & Processing","Magnetic Tape Usage",
 "Magnetic tape is still used today primarily for:",
 "Running operating systems",
 "Enterprise data backup and long-term archival",
 "Real-time web serving",
 "Gaming","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Large corporations like banks use magnetic tape for:",
 "Customer gaming experiences",
 "Disaster recovery and regulatory compliance archival",
 "Social media posting",
 "Video game development","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Magnetic tape libraries in data centers store:",
 "Physical books",
 "Thousands of tape cartridges managed by robotic systems",
 "Coffee supplies",
 "Paper documents","B"),

("Storage & Processing","Magnetic Tape Usage",
 "The cost per terabyte of magnetic tape is:",
 "Much higher than SSD",
 "Significantly lower than SSD or HDD",
 "The same as RAM",
 "Infinite","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Magnetic tape can reliably store data for:",
 "A few hours only",
 "Decades with proper storage conditions",
 "Only one day",
 "Less than a minute","B"),

("Storage & Processing","Magnetic Tape Usage",
 "The tape silo in an enterprise environment is:",
 "A farm building",
 "An automated tape library that stores and retrieves tape cartridges",
 "A grain storage facility",
 "A swimming pool","B"),

("Storage & Processing","Magnetic Tape Usage",
 "WORM (Write Once Read Many) tapes are used for:",
 "Storing earthworms",
 "Regulatory compliance where data must not be altered",
 "Erasing data repeatedly",
 "Playing music","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Offline storage using magnetic tape is called:",
 "Hot storage","Cold storage or nearline storage","Live storage","Active storage","B"),

("Storage & Processing","Magnetic Tape Usage",
 "NASA and CERN use magnetic tape for storing:",
 "Employee photos",
 "Massive volumes of scientific and research data",
 "Office memos only",
 "Cafeteria menus","B"),

("Storage & Processing","Magnetic Tape Usage",
 "The latest LTO-9 tape technology supports native capacity of:",
 "1 MB","18 TB per cartridge","100 bytes","1 KB","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Tape drives read and write data by:",
 "Using laser beams",
 "Moving the tape past a magnetic read/write head",
 "Shining light through the tape",
 "Using sound vibrations","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Magnetic tape is NOT suitable for:",
 "Long-term archival",
 "Frequently accessed databases needing instant response",
 "Backup storage",
 "Disaster recovery copies","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Cloud providers like AWS offer tape-based storage via:",
 "Amazon S3 only",
 "AWS Storage Gateway with virtual tape library",
 "Only physical tape delivery",
 "No tape options at all","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Air-gapped tape backups protect against:",
 "Physical theft only",
 "Ransomware and cyber attacks since tapes are offline",
 "Only fire damage",
 "Nothing at all","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Tape rotation schemes like GFS (Grandfather-Father-Son) ensure:",
 "Tapes are never reused",
 "Organized backup cycles with daily, weekly, and monthly tapes",
 "Only one backup copy exists",
 "Tapes are destroyed daily","B"),

# ── PROGRAMMING TRANSLATORS ── Assembler ──
("Programming Translators","Assembler",
 "An assembler translates:",
 "High-level language to machine code",
 "Assembly language to machine code",
 "Machine code to assembly language",
 "English to French","B"),

("Programming Translators","Assembler",
 "Assembly language is a:",
 "High-level language","Low-level programming language","Markup language","Natural language","B"),

("Programming Translators","Assembler",
 "Assembly language uses:",
 "Natural English sentences",
 "Mnemonics that represent machine instructions",
 "Only numbers in decimal",
 "HTML tags","B"),

("Programming Translators","Assembler",
 "An example of an assembly mnemonic is:",
 "print('hello')","MOV, ADD, SUB, JMP","<html>","SELECT * FROM","B"),

("Programming Translators","Assembler",
 "Assembly language is specific to:",
 "All processor types equally",
 "A particular processor architecture (e.g., x86, ARM)",
 "Only web browsers",
 "Only databases","B"),

("Programming Translators","Assembler",
 "The output of an assembler is:",
 "Source code","Machine code (object code)","HTML page","A PDF document","B"),

("Programming Translators","Assembler",
 "Assembler performs translation:",
 "Simultaneously while running the program",
 "Before execution, converting the entire assembly file to machine code",
 "After the program has finished running",
 "Only during printing","B"),

("Programming Translators","Assembler",
 "Assembly language is considered low-level because it:",
 "Is easy to learn like Python",
 "Closely corresponds to machine instructions of the processor",
 "Has no relation to hardware",
 "Runs in web browsers","B"),

("Programming Translators","Assembler",
 "One assembly language instruction typically translates to:",
 "Many machine language instructions",
 "One machine language instruction",
 "No machine instructions",
 "One complete program","B"),

("Programming Translators","Assembler",
 "NASM and MASM are examples of:",
 "Compilers","Assemblers for x86 architecture","Web servers","Databases","B"),

("Programming Translators","Assembler",
 "Programs written in assembly language tend to be:",
 "Larger than high-level programs for the same task",
 "Very efficient and fast but harder to write and maintain",
 "Slower than Python programs",
 "Identical to HTML programs","B"),

("Programming Translators","Assembler",
 "Assemblers also handle symbolic labels for memory addresses, making code:",
 "Impossible to write",
 "More readable than raw machine code",
 "Less readable",
 "Only usable online","B"),

("Programming Translators","Assembler",
 "A two-pass assembler processes the source code:",
 "Once only","Twice: first to resolve labels, then to generate machine code","Three times","Zero times","B"),

# ── Compiler ──
("Programming Translators","Compiler",
 "A compiler translates:",
 "Assembly language to machine code",
 "An entire high-level language program to machine code at once",
 "Machine code to high-level language",
 "Only comments in the code","B"),

("Programming Translators","Compiler",
 "Which of the following languages is typically compiled?",
 "Python","C","JavaScript","HTML","B"),

("Programming Translators","Compiler",
 "The compiled output is called:",
 "Source code","Object code or executable","Comments","Documentation","B"),

("Programming Translators","Compiler",
 "A compiler checks for errors:",
 "One line at a time during execution",
 "In the entire source code before producing the executable",
 "Only during printing",
 "Never","B"),

("Programming Translators","Compiler",
 "Once a program is compiled successfully, the executable can run:",
 "Only with the compiler present",
 "Without needing the compiler again",
 "Only on the internet",
 "Only once","B"),

("Programming Translators","Compiler",
 "GCC is a well-known compiler for:",
 "Java","C and C++","Python","HTML","B"),

("Programming Translators","Compiler",
 "Compilation produces machine code that is:",
 "Slower than interpreted code",
 "Generally faster to execute than interpreted code",
 "Identical to source code",
 "Only readable by humans","B"),

("Programming Translators","Compiler",
 "A syntax error in a compiled language is detected:",
 "Only at runtime",
 "At compile time before the program runs",
 "Never",
 "After the program finishes","B"),

("Programming Translators","Compiler",
 "The compilation process includes stages like:",
 "Only lexical analysis",
 "Lexical analysis, parsing, optimization, and code generation",
 "Only printing",
 "Only formatting","B"),

("Programming Translators","Compiler",
 "Cross-compilation means compiling code on one platform for:",
 "The same platform only",
 "A different target platform",
 "No platform",
 "Only paper output","B"),

("Programming Translators","Compiler",
 "Java uses a compiler (javac) to produce:",
 "Native machine code directly",
 "Bytecode that runs on the Java Virtual Machine (JVM)",
 "HTML pages",
 "Only text files","B"),

("Programming Translators","Compiler",
 "The optimization phase of a compiler aims to:",
 "Make the code larger",
 "Improve the efficiency and performance of the generated code",
 "Add more bugs",
 "Remove features","B"),

("Programming Translators","Compiler",
 "A linker is used after compilation to:",
 "Delete the object code",
 "Combine object files and libraries into a final executable",
 "Only add comments",
 "Only format the code","B"),

("Programming Translators","Compiler",
 "Compiled programs are not easily portable because:",
 "They run everywhere identically",
 "The machine code is specific to the target processor and OS",
 "They are in plain text",
 "They have no binary output","B"),

# ── Interpreter ──
("Programming Translators","Interpreter",
 "An interpreter translates and executes code:",
 "All at once before running",
 "Line by line (or statement by statement) at runtime",
 "Only after the entire program finishes",
 "Only during printing","B"),

("Programming Translators","Interpreter",
 "Which of the following languages is typically interpreted?",
 "C","C++","Python","Assembly","C"),

("Programming Translators","Interpreter",
 "An interpreter detects errors:",
 "All at once before running",
 "When it encounters the problematic line during execution",
 "Never",
 "Only after the program has fully run","B"),

("Programming Translators","Interpreter",
 "Interpreted programs are generally:",
 "Faster than compiled programs",
 "Slower than compiled programs because translation happens at runtime",
 "Identical in speed to compiled programs",
 "Not executable at all","B"),

("Programming Translators","Interpreter",
 "An advantage of interpreted languages is:",
 "Fastest possible execution speed",
 "Easier debugging since errors are reported line by line",
 "No need for a programming language",
 "No errors ever occur","B"),

("Programming Translators","Interpreter",
 "JavaScript in web browsers is executed by:",
 "A compiler only","A JavaScript engine that interprets/JIT-compiles code","The operating system kernel","The hardware directly","B"),

("Programming Translators","Interpreter",
 "To run an interpreted program, you need:",
 "Only the source code",
 "The interpreter installed on the machine along with the source code",
 "A compiled executable",
 "No software at all","B"),

("Programming Translators","Interpreter",
 "REPL stands for:",
 "Read-Evaluate-Print Loop","Run-Execute-Print Logic","Real-time Evaluation Processing Line","Remote Execution Protocol Link","A"),

("Programming Translators","Interpreter",
 "A REPL allows programmers to:",
 "Only view code",
 "Interactively type code and see results immediately",
 "Only compile programs",
 "Only print documentation","B"),

("Programming Translators","Interpreter",
 "Ruby and PHP are examples of:",
 "Compiled-only languages",
 "Interpreted (or partially interpreted) languages",
 "Machine languages",
 "Assembly languages","B"),

("Programming Translators","Interpreter",
 "Interpreted code is more portable because:",
 "It runs on specific hardware only",
 "The source code can run on any machine with the appropriate interpreter",
 "It generates machine-specific binaries",
 "It has no source code","B"),

("Programming Translators","Interpreter",
 "An interpreter must be present:",
 "Only during compilation",
 "Every time the interpreted program is run",
 "Only during installation",
 "Never","B"),

("Programming Translators","Interpreter",
 "JIT (Just-In-Time) compilation combines benefits of:",
 "Only interpretation",
 "Both interpretation and compilation for improved performance",
 "Only compilation",
 "Neither interpretation nor compilation","B"),

# ── Differences Among All Three ──
("Programming Translators","Differences Among All Three",
 "An assembler works with which type of language?",
 "High-level language","Assembly (low-level) language","Markup language","Natural language","B"),

("Programming Translators","Differences Among All Three",
 "A compiler works with which type of language?",
 "Assembly language only","High-level languages like C, C++","Only machine code","Only HTML","B"),

("Programming Translators","Differences Among All Three",
 "An interpreter works with which type of language?",
 "Only assembly language","High-level languages like Python, Ruby","Only machine code","Only binary","B"),

("Programming Translators","Differences Among All Three",
 "Which translator converts the entire program before execution?",
 "Interpreter","Assembler and Compiler","Neither","Only the debugger","B"),

("Programming Translators","Differences Among All Three",
 "Which translator converts and executes code line by line?",
 "Compiler","Assembler","Interpreter","Linker","C"),

("Programming Translators","Differences Among All Three",
 "After successful compilation, the original source code is:",
 "Required every time the program runs",
 "Not required to run the executable",
 "Automatically deleted",
 "Converted to a PDF","B"),

("Programming Translators","Differences Among All Three",
 "After interpretation, there is:",
 "A standalone executable file",
 "No separate executable; the interpreter must be present to run the program",
 "A compiled binary always",
 "A printed document","B"),

("Programming Translators","Differences Among All Three",
 "Compilation produces code that runs:",
 "Slower than interpreted code generally",
 "Faster than interpreted code generally",
 "At the same speed as interpreted code",
 "Not at all","B"),

("Programming Translators","Differences Among All Three",
 "Error detection in a compiler happens:",
 "Line by line during execution",
 "During compilation, before the program runs",
 "Only after the program has run completely",
 "It never detects errors","B"),

("Programming Translators","Differences Among All Three",
 "Error detection in an interpreter happens:",
 "All at once before execution",
 "When the problematic line is reached during execution",
 "Never",
 "Only during printing","B"),

("Programming Translators","Differences Among All Three",
 "Assembly language is closest in structure to:",
 "English prose","Machine code","Python","HTML","B"),

("Programming Translators","Differences Among All Three",
 "High-level languages are designed to be:",
 "Hard for humans to read",
 "Closer to human language and easier for programmers",
 "Identical to machine code",
 "Only usable by machines","B"),

("Programming Translators","Differences Among All Three",
 "The correct mapping is: Assembler -> Assembly; Compiler -> ?",
 "Machine code directly",
 "High-level language (like C, C++, Java)",
 "Only Python",
 "Only HTML","B"),

("Programming Translators","Differences Among All Three",
 "Which combination is correct?",
 "Compiler: line by line; Interpreter: all at once",
 "Compiler: entire program at once; Interpreter: line by line",
 "Both work identically",
 "Neither translates code","B"),

("Programming Translators","Differences Among All Three",
 "A program that converts a high-level language directly into machine code in one pass is an example of a:",
 "Interpreter","Compiler","Assembler","Debugger","B"),

("Programming Translators","Differences Among All Three",
 "For rapid prototyping and testing, which approach is preferred?",
 "Compilation (slower cycle of edit-compile-run)",
 "Interpretation (quick edit-run cycle with immediate feedback)",
 "Neither approach works",
 "Assembly language only","B"),

("Programming Translators","Differences Among All Three",
 "For performance-critical production software, which approach is preferred?",
 "Interpretation for maximum speed",
 "Compilation for optimized native machine code",
 "Neither approach",
 "Manual binary editing","B"),

("Programming Translators","Differences Among All Three",
 "Some languages like Java use both compilation and interpretation because:",
 "They cannot decide which to use",
 "Source code is compiled to bytecode, then interpreted/JIT-compiled by the JVM",
 "They only run on paper",
 "Neither technique works for Java","B"),

("Programming Translators","Differences Among All Three",
 "The role of any programming translator is to convert:",
 "Hardware to software",
 "Human-readable code into machine-executable instructions",
 "Electricity into code",
 "Paper into digital format","B"),

("Programming Translators","Differences Among All Three",
 "Without translators, programmers would have to write programs in:",
 "Python","Raw binary machine code (0s and 1s)","English","HTML","B"),
]
