# Section 1 Supplementary Questions (242 additional) to reach exactly 1000
# Covers all topics with additional depth
# Format: (topic, subtopic, question, optA, optB, optC, optD, answer)

def get_questions():
    return [
# ── CLOUD COMPUTING ── additional ──
("Cloud Computing","Definition of Cloud Computing",
 "NIST identifies how many essential characteristics of cloud computing?",
 "Three","Five","Ten","Seven","B"),

("Cloud Computing","Definition of Cloud Computing",
 "Rapid elasticity is a cloud characteristic that allows resources to be:",
 "Fixed permanently",
 "Scaled rapidly outward and inward based on demand",
 "Deleted automatically every week",
 "Only used once","B"),

("Cloud Computing","Cloud Storage Concept",
 "Which company offers Google Cloud Storage for enterprise data?",
 "Microsoft","Amazon","Google","IBM","C"),

("Cloud Computing","Cloud Storage Concept",
 "End-to-end encryption in cloud storage ensures:",
 "Anyone can read the data",
 "Data is encrypted during transfer and while stored",
 "Data is never stored",
 "Only the provider can read data","B"),

("Cloud Computing","Examples of Cloud Usage",
 "Using Canva online to design posters is an example of:",
 "Local computing only","Cloud-based SaaS","Hardware usage","Manual design","B"),

("Cloud Computing","Examples of Cloud Usage",
 "WhatsApp stores chat backups on:",
 "The SIM card only","Cloud services like Google Drive or iCloud","The phone battery","The charger","B"),

("Cloud Computing","Advantages of Cloud Computing",
 "Cloud computing supports remote work by providing:",
 "No access to any tools",
 "Access to work tools and data from any location",
 "Only office-based access",
 "Only printing capability","B"),

("Cloud Computing","Advantages of Cloud Computing",
 "Multi-region deployment in cloud computing ensures:",
 "All data is in one room",
 "High availability even if one region goes down",
 "Slower performance",
 "No data storage","B"),

("Cloud Computing","Pay-per-use Model",
 "Cloud providers use dashboards to help customers:",
 "Ignore their bills",
 "Monitor and control their cloud spending in real time",
 "Hide their usage",
 "Delete their accounts","B"),

("Cloud Computing","Remote Access Concept",
 "Single Sign-On (SSO) simplifies cloud remote access by:",
 "Requiring separate passwords for every app",
 "Allowing users to log in once to access multiple cloud services",
 "Disabling all security",
 "Requiring no login at all","B"),

# ── CLOUD SERVICE PROVIDERS ── additional ──
("Cloud Service Providers","Amazon Web Services (AWS)",
 "AWS CloudFormation is used for:",
 "Weather forecasting",
 "Infrastructure as Code to automate resource provisioning",
 "Email marketing",
 "Video editing","B"),

("Cloud Service Providers","Amazon Web Services (AWS)",
 "Amazon Glacier is designed for:",
 "Real-time data processing","Low-cost long-term archival storage","Video streaming","Gaming","B"),

("Cloud Service Providers","Microsoft Azure",
 "Azure Logic Apps is used for:",
 "Photo editing","Automating workflows and integrating apps without code","Gaming","Music production","B"),

("Cloud Service Providers","Microsoft Azure",
 "Azure CDN stands for:",
 "Content Design Network","Content Delivery Network","Computer Data Node","Central Domain Name","B"),

("Cloud Service Providers","Difference: AWS vs Azure",
 "Google Cloud Platform (GCP) is the third-largest cloud provider after:",
 "IBM and Oracle","AWS and Azure","Apple and Samsung","Dell and HP","B"),

("Cloud Service Providers","Difference: AWS vs Azure",
 "Multi-cloud strategy means using:",
 "Only one cloud provider",
 "Services from multiple cloud providers simultaneously",
 "No cloud at all",
 "Only on-premise servers","B"),

# ── CLOUD SERVICE MODELS ── additional ──
("Cloud Service Models","SaaS - Definition",
 "In SaaS, software updates are handled by:",
 "Each individual user manually",
 "The SaaS provider, applied automatically for all users",
 "The hardware manufacturer",
 "No one","B"),

("Cloud Service Models","SaaS Examples",
 "GitHub, a code hosting platform, operates as:",
 "IaaS","PaaS only","SaaS","Hardware","C"),

("Cloud Service Models","SaaS Examples",
 "Notion, a productivity tool, is classified as:",
 "SaaS","IaaS","PaaS","A hardware device","A"),

("Cloud Service Models","PaaS - Definition",
 "PaaS abstracts away infrastructure management so developers can focus on:",
 "Hardware procurement","Writing and deploying application code","Cable management","Server room maintenance","B"),

("Cloud Service Models","PaaS Examples",
 "Render and Railway are modern examples of:",
 "IaaS providers","PaaS platforms for deploying web applications","Email clients","Operating systems","B"),

("Cloud Service Models","IaaS - Definition",
 "Digital Ocean Droplets provide virtual servers and are an example of:",
 "SaaS","PaaS","IaaS","FaaS","C"),

("Cloud Service Models","IaaS - Definition",
 "Linode is a cloud provider known for its:",
 "SaaS applications","IaaS offerings like virtual servers and storage","Social media platform","Gaming console","B"),

("Cloud Service Models","Difference: SaaS vs PaaS vs IaaS",
 "FaaS (Function as a Service) is a subset of:",
 "SaaS","IaaS","PaaS / Serverless computing","Hardware","C"),

("Cloud Service Models","Difference: SaaS vs PaaS vs IaaS",
 "BaaS (Backend as a Service) provides:",
 "Physical backend hardware",
 "Pre-built backend features like databases, auth, and push notifications",
 "Only email services",
 "Only file hosting","B"),

("Cloud Service Models","Difference: SaaS vs PaaS vs IaaS",
 "The shared responsibility model in cloud defines:",
 "That the customer does everything",
 "Which security tasks belong to the provider vs the customer depending on the service model",
 "That the provider does everything always",
 "That neither party has responsibility","B"),

# ── CLOUD DEPLOYMENT MODELS ── additional ──
("Cloud Deployment Models","Public Cloud",
 "The public cloud follows a shared tenancy model where:",
 "Each user owns the physical hardware",
 "Resources are shared among many users securely",
 "Only one user exists",
 "No sharing occurs","B"),

("Cloud Deployment Models","Private Cloud",
 "A virtual private cloud (VPC) within a public cloud provides:",
 "No isolation at all",
 "An isolated virtual network for a single customer within a public cloud",
 "A physical private data center",
 "A home network","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Data residency requirements may push organizations toward hybrid cloud to:",
 "Store all data publicly",
 "Keep sensitive data on-premises while using cloud for other workloads",
 "Delete all data",
 "Use social media for storage","B"),

("Cloud Deployment Models","Use-case Based Differences",
 "A media company streaming content globally while keeping editorial systems private uses:",
 "Only public cloud","Only private cloud","Hybrid cloud","No cloud at all","C"),

("Cloud Deployment Models","Use-case Based Differences",
 "Multi-cloud deploys workloads across:",
 "Zero providers","One provider only","Multiple cloud providers like AWS and Azure simultaneously","No technology","C"),

# ── VIRTUALIZATION ── additional ──
("Virtualization & Architecture","Virtualization Definition",
 "Containerization (e.g., Docker) is an alternative to full virtualization that:",
 "Uses more resources than VMs",
 "Shares the host OS kernel, making containers lightweight",
 "Requires a separate hypervisor for each container",
 "Uses no computing resources","B"),

("Virtualization & Architecture","Virtualization Definition",
 "A snapshot of a virtual machine captures:",
 "A photograph of the physical server",
 "The complete state of the VM at a point in time for backup or rollback",
 "Only the network settings",
 "Only the display resolution","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "Xen is a Type 1 hypervisor used by:",
 "Only home computers","AWS (historically) and Citrix","Only printers","Only cameras","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "Proxmox is an open-source platform that supports:",
 "Only gaming",
 "Both KVM virtual machines and LXC containers",
 "Only email",
 "Only printing","B"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "Live migration allows a running VM to be moved between physical hosts:",
 "Only when turned off",
 "Without downtime, while the VM continues running",
 "Only by deleting it first",
 "Only once per year","B"),

("Virtualization & Architecture","Single Physical Resource Sharing",
 "Resource overcommitment allows virtual allocations to exceed physical capacity because:",
 "Not all VMs use maximum resources simultaneously",
 "Physical resources are unlimited",
 "No monitoring is needed",
 "Each VM has its own data center","A"),

("Virtualization & Architecture","Virtual Machine Isolation",
 "Security groups and micro-segmentation in cloud enforce:",
 "No security at all",
 "Fine-grained network isolation between virtual workloads",
 "Universal access for everyone",
 "Physical walls between servers","B"),

# ── UTILITY & GRID ── additional ──
("Utility & Grid Computing","Utility Computing Definition",
 "Amazon Web Services is a modern realization of the utility computing vision because:",
 "It sells physical hardware only",
 "It provides computing resources on demand with metered billing",
 "It has no billing system",
 "It only offers free services","B"),

("Utility & Grid Computing","Pay-per-use Concept",
 "Reserved instances in cloud provide discounts for:",
 "No commitment at all",
 "Committing to a certain usage level over a period",
 "Using resources for free",
 "Only one hour of usage","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "Folding@home is a grid computing project that:",
 "Folds paper digitally",
 "Uses distributed volunteer computers to simulate protein folding for disease research",
 "Only sorts files",
 "Only sends emails","B"),

("Utility & Grid Computing","Heterogeneous Resources",
 "Middleware like Globus enables grid computing across heterogeneous systems by providing:",
 "Physical standardization of hardware",
 "A standard software layer for resource discovery, job management, and security",
 "No software at all",
 "Only email service","B"),

("Utility & Grid Computing","Geographically Dispersed Systems",
 "The Large Hadron Collider (LHC) Computing Grid connects institutions in:",
 "Only one city","Over 40 countries worldwide","Only two buildings","No locations","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Cloud computing offers better self-service interfaces than grid computing through:",
 "Physical buttons",
 "Web-based consoles, CLIs, and APIs",
 "Postal mail requests",
 "Telephone-only service","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Grid computing focuses on batch processing while cloud computing also supports:",
 "Only batch processing",
 "Real-time interactive applications and services",
 "Only paper-based outputs",
 "Only backup operations","B"),

# ── SOA & MANAGED SERVICES ── additional ──
("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "Microservices architecture evolved from SOA and differs by using:",
 "Larger monolithic services",
 "Small, independently deployable services with lightweight protocols",
 "No services at all",
 "Only one service per company","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "API Gateway in SOA and microservices is used to:",
 "Block all traffic",
 "Manage, route, and secure API requests between clients and services",
 "Only store data",
 "Only print reports","B"),

("SOA & Managed Services","Managed IT Services",
 "NOC (Network Operations Center) in managed services:",
 "Monitors and manages network performance 24/7",
 "Only sells hardware",
 "Only designs logos",
 "Only writes blog posts","A"),

("SOA & Managed Services","Managed IT Services",
 "Managed backup services ensure:",
 "No backups are ever taken",
 "Regular automated backups with tested recovery procedures",
 "Only manual paper copies",
 "Backups happen once a decade","B"),

("SOA & Managed Services","Client-Server Model",
 "A proxy server in client-server architecture acts as:",
 "A replacement for the client",
 "An intermediary between clients and servers for security and caching",
 "The main database",
 "A keyboard replacement","B"),

("SOA & Managed Services","Client-Server Model",
 "A DNS server resolves:",
 "Physical addresses of buildings",
 "Domain names to IP addresses so clients can reach servers",
 "Only email addresses",
 "Only phone numbers","B"),

# ── CLIENT & GUI ── additional ──
("Client & GUI","Client Definition",
 "A smart TV streaming Netflix acts as a:",
 "Server","Client requesting content from Netflix servers","Router","Switch","B"),

("Client & GUI","Client Definition",
 "Chromebooks are thin client devices because they rely primarily on:",
 "Local heavy processing",
 "Cloud-based applications and storage",
 "No external services",
 "Only offline apps","B"),

("Client & GUI","GUI Definition",
 "A dialog box in a GUI is:",
 "A text-only command line",
 "A small window that prompts the user for input or displays information",
 "A physical box",
 "A type of printer","B"),

("Client & GUI","GUI Definition",
 "A GUI toolbar contains:",
 "Physical tools",
 "Buttons and icons for quick access to frequently used commands",
 "Only text",
 "Only advertisements","B"),

("Client & GUI","Application Layer Role",
 "DHCP at the application layer assigns:",
 "Physical addresses to buildings",
 "IP addresses to devices on a network automatically",
 "Only email addresses",
 "Only web addresses","B"),

("Client & GUI","Application Layer Role",
 "NTP (Network Time Protocol) at the application layer synchronizes:",
 "Data files only",
 "Clock times across computers in a network",
 "Printer queues only",
 "Only download speeds","B"),

("Client & GUI","Client-Server Interaction",
 "WebSocket enables:",
 "Only one-way communication",
 "Full-duplex (two-way) real-time communication between client and server",
 "No communication at all",
 "Only physical connections","B"),

("Client & GUI","Client-Server Interaction",
 "Caching on the client side reduces server load by:",
 "Deleting all local data",
 "Storing frequently accessed data locally to avoid repeated server requests",
 "Sending more requests to the server",
 "Ignoring the server completely","B"),

# ── MEMORY ── additional ──
("Memory","Primary Memory (RAM)",
 "ECC RAM (Error-Correcting Code) is used in servers because it:",
 "Is cheaper than regular RAM",
 "Detects and corrects single-bit memory errors for reliability",
 "Is only for gaming",
 "Has no error detection capability","B"),

("Memory","Primary Memory (RAM)",
 "SO-DIMM is a smaller RAM form factor used in:",
 "Desktop towers only","Laptops and small form factor computers","Printers","Calculators","B"),

("Memory","Secondary Memory",
 "NVMe is a storage protocol designed for:",
 "Floppy disks",
 "High-speed SSDs connected via PCIe interface",
 "Magnetic tapes only",
 "Paper storage","B"),

("Memory","Secondary Memory",
 "RAID (Redundant Array of Independent Disks) is used to:",
 "Play music",
 "Improve storage performance and/or provide data redundancy",
 "Only delete files",
 "Only compress images","B"),

("Memory","Magnetic Tape",
 "Tape autoloaders differ from tape libraries in that autoloaders are:",
 "Larger and hold more tapes",
 "Smaller, holding fewer tapes with simpler robotics",
 "Not used for tape at all",
 "Identical to libraries","B"),

("Memory","Magnetic Tape",
 "Data written to magnetic tape is organized in:",
 "Random patterns","Linear tracks along the length of the tape","Circular patterns like a CD","No patterns at all","B"),

("Memory","Hard Disk",
 "The actuator arm in an HDD moves the read/write head to:",
 "The power supply",
 "The correct track on the platter to read or write data",
 "The USB port",
 "The keyboard","B"),

("Memory","Hard Disk",
 "A partition on a hard disk is:",
 "A physical crack in the disk",
 "A logically separated section of the disk treated as a separate volume",
 "A type of virus",
 "A display setting","B"),

("Memory","Floppy Disk",
 "The write-protect tab on a floppy disk:",
 "Increases storage capacity",
 "Prevents data from being written or deleted",
 "Formats the disk automatically",
 "Changes the disk color","B"),

("Memory","RAM vs Secondary Memory",
 "The memory hierarchy from fastest to slowest is:",
 "Hard disk -> RAM -> Cache -> CPU Registers",
 "CPU Registers -> Cache -> RAM -> Secondary Storage",
 "Secondary Storage -> RAM -> CPU Registers -> Cache",
 "RAM -> CPU Registers -> Cache -> Hard disk","B"),

# ── INPUT/OUTPUT ── additional ──
("Input/Output Devices","Laser Printer",
 "PostScript and PCL are page description languages used by laser printers to:",
 "Connect to the internet",
 "Interpret and render print jobs accurately",
 "Play music",
 "Store photos","B"),

("Input/Output Devices","Laser Printer",
 "A multifunction laser printer (MFP) can:",
 "Only print",
 "Print, scan, copy, and sometimes fax",
 "Only scan",
 "Only copy","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "Warm-up time in laser printers refers to:",
 "Time to unpack the printer",
 "Time for the fuser to reach operating temperature before printing starts",
 "Time to refill toner",
 "Time to connect to Wi-Fi","B"),

("Input/Output Devices","DPI vs PPM",
 "A large format plotter typically has high DPI but lower PPM because:",
 "It prints on small paper",
 "Large detailed prints require more time per page",
 "It never prints anything",
 "It only prints fast drafts","B"),

# ── KEYBOARD & HARDWARE ── additional ──
("Keyboard & Hardware","ESC Key",
 "In many programming IDEs, ESC is used to:",
 "Compile code",
 "Close autocomplete suggestions or dismiss popups",
 "Run the program",
 "Save the file","B"),

("Keyboard & Hardware","Enter Key",
 "In chat applications, pressing Enter usually:",
 "Deletes the message","Sends the message","Closes the chat","Opens settings","B"),

("Keyboard & Hardware","Delete Key",
 "Fn + Backspace on some compact keyboards acts as the:",
 "Escape key","Delete key","Enter key","Tab key","B"),

("Keyboard & Hardware","Insert Key",
 "The status bar in some text editors shows OVR when:",
 "The file is read-only",
 "Overtype mode is active (Insert key toggled)",
 "The file is new",
 "The printer is connected","B"),

# ── COMPUTER HARDWARE BASICS ── additional ──
("Computer Hardware Basics","Semiconductor Definition",
 "A MOSFET (Metal-Oxide-Semiconductor Field-Effect Transistor) is the basic building block of:",
 "Paper circuits","Modern digital integrated circuits","Wooden structures","Glass products","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Gallium Arsenide (GaAs) is a semiconductor used in:",
 "Only light switches",
 "High-speed electronics and optoelectronic devices",
 "Only paper products",
 "Only wooden structures","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "Die size in chip manufacturing refers to:",
 "The physical size of a single chip cut from a silicon wafer",
 "The size of the packaging box",
 "The color of the chip",
 "The weight of the chip","A"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "Yield in chip manufacturing is the percentage of:",
 "Workers in the factory",
 "Functional chips produced from a wafer out of total chips",
 "Wafers that are round",
 "Boxes that are shipped","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "A system-on-chip (SoC) integrates:",
 "Only a CPU",
 "CPU, GPU, memory controller, and other components on a single chip",
 "Only storage",
 "Only networking","B"),

# ── TYPES OF COMPUTERS ── additional ──
("Types of Computers","Analog Computer",
 "An analog voltmeter using a needle to display voltage is an:",
 "Digital device","Analog measurement device","Hybrid device","No computing device","B"),

("Types of Computers","Analog Computer",
 "Tide prediction machines of the early 20th century were:",
 "Digital computers","Analog computers","Quantum computers","No computers","B"),

("Types of Computers","Digital Computer",
 "A 64-bit processor can handle data in chunks of:",
 "8 bits","16 bits","32 bits","64 bits","D"),

("Types of Computers","Digital Computer",
 "The Von Neumann architecture describes a digital computer with:",
 "No memory at all",
 "A stored program concept with CPU, memory, and I/O",
 "Only analog circuits",
 "Only output devices","B"),

("Types of Computers","Digital Computer",
 "A supercomputer is a type of digital computer designed for:",
 "Simple text editing",
 "Extremely fast processing of complex calculations",
 "Only email",
 "Only web browsing","B"),

("Types of Computers","Hybrid Computer",
 "The Analog-to-Digital Converter (ADC) in a hybrid computer converts:",
 "Digital signals to analog",
 "Continuous analog signals to discrete digital values",
 "Text to images",
 "Sound to light","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Smart home thermostats are hybrid because they:",
 "Only display temperature",
 "Measure analog temperature and digitally control heating/cooling systems",
 "Only play music",
 "Only connect to Wi-Fi","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Modern audio recording uses hybrid computing to:",
 "Only play CDs",
 "Capture analog sound waves and convert them to digital format",
 "Only print lyrics",
 "Only store physical tapes","B"),

# ── STORAGE & PROCESSING ── additional ──
("Storage & Processing","Sequential Access Devices",
 "Random access memory (RAM) allows any byte to be accessed without reading preceding bytes, unlike:",
 "SSD","Sequential access devices like magnetic tape","Other RAM modules","The CPU","B"),

("Storage & Processing","Sequential Access Devices",
 "Direct access storage devices (DASD) like hard disks use:",
 "Strictly sequential access",
 "A combination of direct positioning and short sequential reads",
 "No access at all",
 "Only cloud access","B"),

("Storage & Processing","Magnetic Tape Usage",
 "The 3-2-1 backup rule recommends keeping at least one backup copy on:",
 "The same computer only",
 "An offsite medium like magnetic tape for disaster recovery",
 "A sticky note",
 "The monitor screen","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Tape encryption protects stored data by:",
 "Making the tape physically heavier",
 "Encrypting data before writing it to tape so unauthorized access is prevented",
 "Changing the tape color",
 "Making the tape unreadable by anyone","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Tape is considered green storage because:",
 "Tapes are colored green",
 "Idle tapes consume zero power compared to spinning disks",
 "They are made from plants",
 "They generate electricity","B"),

# ── PROGRAMMING TRANSLATORS ── additional ──
("Programming Translators","Assembler",
 "Inline assembly allows programmers to:",
 "Write only in Python",
 "Embed assembly instructions within high-level language code for performance",
 "Only use HTML",
 "Avoid all programming","B"),

("Programming Translators","Assembler",
 "A disassembler performs the reverse of an assembler by converting:",
 "Assembly to machine code",
 "Machine code back to assembly language for analysis",
 "HTML to CSS",
 "English to French","B"),

("Programming Translators","Compiler",
 "Ahead-of-Time (AOT) compilation means:",
 "Compilation happens during runtime",
 "The entire program is compiled before execution for maximum performance",
 "No compilation occurs",
 "Only partial compilation happens","B"),

("Programming Translators","Compiler",
 "A lexer (lexical analyzer) in a compiler breaks source code into:",
 "Physical pieces",
 "Tokens (keywords, identifiers, operators, literals)",
 "Paper strips",
 "Random characters","B"),

("Programming Translators","Compiler",
 "A parser in a compiler checks:",
 "Only spelling",
 "Whether the token sequence follows the grammar rules of the language",
 "Only file size",
 "Only file extension","B"),

("Programming Translators","Compiler",
 "An abstract syntax tree (AST) represents:",
 "A physical tree",
 "The hierarchical structure of the source code after parsing",
 "A file directory",
 "A network topology","B"),

("Programming Translators","Interpreter",
 "CPython is the default interpreter for:",
 "C language","Python","Java","Ruby","B"),

("Programming Translators","Interpreter",
 "PyPy is an alternative Python interpreter that uses JIT compilation to:",
 "Slow down programs",
 "Speed up Python execution compared to CPython",
 "Remove all features",
 "Only work offline","B"),

("Programming Translators","Interpreter",
 "An interpreted language's source code is distributed instead of binaries, which means:",
 "Source code is hidden from everyone",
 "Users can see and modify the source code",
 "The code never runs",
 "The code is encrypted always","B"),

("Programming Translators","Differences Among All Three",
 "Bytecode is an intermediate form used by languages like Java and Python that is executed by a:",
 "Physical machine directly",
 "Virtual machine or interpreter",
 "Paper printer",
 "Analog computer","B"),

("Programming Translators","Differences Among All Three",
 "Transpilers convert source code from one high-level language to:",
 "Machine code directly",
 "Another high-level language (e.g., TypeScript to JavaScript)",
 "Assembly language",
 "Binary only","B"),

("Programming Translators","Differences Among All Three",
 "A debugger is NOT a translator but helps programmers find:",
 "New features to add",
 "Bugs and errors in the code during execution",
 "New employees",
 "The internet","B"),

# ── Additional coverage: Networking Basics ──
("Computer Hardware Basics","Semiconductor Definition",
 "Silicon-on-Insulator (SOI) technology improves chip performance by:",
 "Adding more weight",
 "Reducing parasitic capacitance for faster switching",
 "Making chips larger",
 "Only changing the color","B"),

("Cloud Computing","Definition of Cloud Computing",
 "Serverless computing does NOT mean there are no servers; it means:",
 "Servers are physically absent",
 "Server management is abstracted away from the developer",
 "Only one server exists worldwide",
 "Servers run without electricity","B"),

("Cloud Computing","Advantages of Cloud Computing",
 "Cloud computing enables DevOps practices by providing:",
 "No automation tools",
 "Infrastructure automation, CI/CD pipelines, and scalable environments",
 "Only manual deployments",
 "Only paper-based tracking","B"),

("Cloud Service Models","Difference: SaaS vs PaaS vs IaaS",
 "CaaS (Container as a Service) provides:",
 "Only email containers",
 "Container orchestration and management as a cloud service",
 "Physical shipping containers",
 "Only storage containers","B"),

("Cloud Deployment Models","Hybrid Cloud",
 "Latency-sensitive applications in hybrid cloud keep compute resources:",
 "Only in the public cloud far away",
 "Close to the data source, often on-premises or at edge locations",
 "Only in space",
 "Nowhere at all","B"),

("Virtualization & Architecture","Virtualization Definition",
 "GPU virtualization allows multiple VMs to share:",
 "Only CPU resources",
 "A single physical GPU for graphics and compute workloads",
 "Only storage",
 "Only networking","B"),

("Memory","Primary Memory (RAM)",
 "Dual-channel RAM improves performance by:",
 "Using only one memory slot",
 "Doubling the bandwidth by using two memory channels simultaneously",
 "Halving the RAM capacity",
 "Removing error correction","B"),

("Memory","Secondary Memory",
 "M.2 is a form factor for SSDs that connects directly to the motherboard via:",
 "USB cable","M.2 slot supporting NVMe or SATA protocols","Audio jack","HDMI port","B"),

("Memory","Hard Disk",
 "Helium-filled HDDs improve performance by:",
 "Adding weight",
 "Reducing internal air resistance, allowing thinner platters and higher capacity",
 "Making the drive louder",
 "Increasing heat generation","B"),

("Memory","RAM vs Secondary Memory",
 "Optane Memory by Intel bridges the gap between RAM and storage by providing:",
 "No speed improvement",
 "Very fast non-volatile storage that accelerates frequently accessed data",
 "Only RAM replacement",
 "Only tape backup","B"),

("Input/Output Devices","Laser Printer",
 "A laser printer drum unit needs replacement when:",
 "The printer is brand new",
 "Print quality degrades with streaks or faded areas",
 "The toner is full",
 "The paper tray is empty","B"),

("Input/Output Devices","DPI vs PPM",
 "Effective DPI may differ from optical DPI because:",
 "They are always identical",
 "Software interpolation can enhance apparent resolution beyond hardware capability",
 "DPI cannot be measured",
 "PPM determines DPI","B"),

("Keyboard & Hardware","ESC Key",
 "In PowerPoint presentation mode, pressing ESC:",
 "Starts the slideshow",
 "Exits the slideshow and returns to editing mode",
 "Prints the slides",
 "Deletes all slides","B"),

("Keyboard & Hardware","Enter Key",
 "Alt + Enter in Excel lets you:",
 "Delete a cell",
 "Insert a line break within a cell",
 "Exit Excel",
 "Print the sheet","B"),

("Types of Computers","Digital Computer",
 "An embedded system is a specialized digital computer found in:",
 "Only supercomputers",
 "Everyday devices like washing machines, cars, and microwaves",
 "Only laptops",
 "Only servers","B"),

("Types of Computers","Digital Computer",
 "A mainframe computer is designed for:",
 "Personal gaming",
 "Large-scale data processing for enterprises and governments",
 "Only home use",
 "Only mobile computing","B"),

("Storage & Processing","Sequential Access Devices",
 "Streaming media on the internet uses sequential delivery where data arrives:",
 "All at once instantly",
 "In order from beginning to end for continuous playback",
 "In random order",
 "Backwards only","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Linear Tape File System (LTFS) allows magnetic tape to be:",
 "Used only with proprietary software",
 "Accessed like a regular disk drive with drag-and-drop file operations",
 "Read by any web browser",
 "Only used for audio recording","B"),

("Programming Translators","Compiler",
 "LLVM is a compiler infrastructure used by languages like Swift and Rust for:",
 "Only text formatting",
 "Generating optimized intermediate representation and machine code",
 "Only sending emails",
 "Only database management","B"),

("Programming Translators","Interpreter",
 "Node.js uses the V8 engine which employs JIT compilation to execute:",
 "Only Python code",
 "JavaScript code at near-native performance",
 "Only HTML",
 "Only CSS","B"),

("Programming Translators","Differences Among All Three",
 "The choice between compiling and interpreting depends on priorities like:",
 "Only the programmer's name",
 "Execution speed, development speed, portability, and debugging ease",
 "Only the computer's color",
 "Only the time of day","B"),

("Cloud Computing","Cloud Storage Concept",
 "Object storage like Amazon S3 stores data as objects rather than:",
 "Nothing",
 "Hierarchical file systems or block storage",
 "Only images",
 "Only text","B"),

("Cloud Computing","Advantages of Cloud Computing",
 "Compliance certifications like SOC 2, ISO 27001, and HIPAA are offered by cloud providers to:",
 "Increase confusion",
 "Assure customers that security and privacy standards are met",
 "Avoid all security measures",
 "Only for marketing purposes","B"),

("Cloud Service Providers","Amazon Web Services (AWS)",
 "AWS Well-Architected Framework provides guidance on:",
 "Building physical buildings",
 "Designing reliable, secure, efficient, and cost-effective cloud systems",
 "Only pricing information",
 "Only employee management","B"),

("Cloud Service Providers","Microsoft Azure",
 "Azure Sentinel is a cloud-native:",
 "Word processor",
 "Security information and event management (SIEM) solution",
 "Email client",
 "Photo editor","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "Service mesh in modern architectures manages:",
 "Physical server placement",
 "Service-to-service communication, observability, and security",
 "Only email routing",
 "Only file storage","B"),

("SOA & Managed Services","Managed IT Services",
 "A managed service provider's helpdesk offers:",
 "Only hardware sales",
 "First-line technical support for end users",
 "Only catering services",
 "Only travel booking","B"),

("Client & GUI","GUI Definition",
 "Accessibility features in GUIs include:",
 "Removing all visual elements",
 "Screen readers, high contrast modes, and keyboard navigation support",
 "Only using command line",
 "Only physical buttons","B"),

("Client & GUI","Client-Server Interaction",
 "GraphQL is an alternative to REST APIs that allows clients to:",
 "Only receive fixed data structures",
 "Request exactly the data they need in a single query",
 "Avoid all communication with servers",
 "Only send data, never receive","B"),

("Memory","Primary Memory (RAM)",
 "LPDDR5 is a type of RAM optimized for:",
 "Desktop computers only",
 "Mobile devices with low power consumption",
 "Printers",
 "Speakers","B"),

("Memory","Secondary Memory",
 "Cloud storage can be considered virtual secondary storage because:",
 "It uses physical disks at the user's location",
 "Data is stored on remote servers but appears as accessible storage to the user",
 "No data is stored anywhere",
 "It only stores data temporarily","B"),

("Input/Output Devices","Laser Printer",
 "Network-capable laser printers connect via:",
 "Only USB",
 "Ethernet or Wi-Fi for shared access across multiple computers",
 "Only Bluetooth",
 "Only infrared","B"),

("Keyboard & Hardware","Delete Key",
 "In macOS, the Delete key (labeled delete) functions as:",
 "The Windows Delete key",
 "Backspace (removing characters to the left of the cursor)",
 "Enter key",
 "Escape key","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "The semiconductor shortage of 2020-2023 affected industries including:",
 "Only toy manufacturing",
 "Automotive, consumer electronics, and computing",
 "Only food production",
 "Only textile manufacturing","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "A digital oscilloscope is a hybrid device that captures analog electrical signals and:",
 "Only stores them on paper",
 "Displays them as digital waveforms on a screen for analysis",
 "Only deletes them",
 "Only prints them","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Many cloud data centers still use magnetic tape for their cold storage tiers because of:",
 "Speed advantages over SSD",
 "Extremely low cost per terabyte and long-term durability",
 "Faster random access than HDDs",
 "Small physical size","B"),

("Programming Translators","Assembler",
 "Device drivers may use assembly language for:",
 "Only web browsing",
 "Direct hardware access and performance-critical code sections",
 "Only database queries",
 "Only user interfaces","B"),

("Programming Translators","Compiler",
 "Rust is a compiled language known for:",
 "Being slow and unsafe",
 "Memory safety without garbage collection and high performance",
 "Only running on one platform",
 "Being interpreted","B"),

("Programming Translators","Interpreter",
 "The Lua interpreter is popular in:",
 "Only enterprise databases",
 "Game development for embedded scripting",
 "Only web browsers",
 "Only medical devices","B"),

("Cloud Computing","Definition of Cloud Computing",
 "Edge computing extends cloud computing by:",
 "Moving all processing to the central cloud",
 "Processing data closer to the source for lower latency",
 "Eliminating all computing",
 "Only using mainframes","B"),

("Cloud Computing","Remote Access Concept",
 "Zero Trust security in cloud remote access means:",
 "Everyone is trusted by default",
 "No user or device is trusted by default; continuous verification is required",
 "Security is not needed",
 "Only internal users need authentication","B"),

("Cloud Service Models","SaaS - Definition",
 "Vertical SaaS serves:",
 "All industries equally",
 "A specific industry like healthcare, education, or finance",
 "Only the technology sector",
 "Only government agencies","B"),

("Cloud Deployment Models","Public Cloud",
 "Sovereign cloud provides public cloud services that comply with:",
 "No regulations",
 "A specific country's data sovereignty and regulatory requirements",
 "Only US regulations",
 "Only EU regulations","B"),

("Virtualization & Architecture","Virtual Machine Isolation",
 "Side-channel attacks exploit shared hardware to potentially:",
 "Improve performance",
 "Extract data from other VMs on the same physical host",
 "Speed up all VMs",
 "Fix hardware bugs","B"),

("Memory","Secondary Memory",
 "QLC (Quad-Level Cell) NAND flash stores how many bits per cell?",
 "1 bit","2 bits","3 bits","4 bits","D"),

("Input/Output Devices","Printer Speed (PPM)",
 "Production-class printers used in publishing can exceed:",
 "10 PPM","50 PPM","100 PPM easily, some reaching thousands per hour","5 PPM maximum","C"),

("Computer Hardware Basics","Semiconductor Definition",
 "Quantum computing aims to use quantum bits (qubits) which differ from semiconductor transistors by:",
 "Being identical in function",
 "Existing in superposition states of 0 and 1 simultaneously",
 "Being larger than transistors",
 "Using only analog signals","B"),

("Types of Computers","Digital Computer",
 "A GPU (Graphics Processing Unit) in a digital computer is optimized for:",
 "Only text processing",
 "Parallel processing of graphics and compute-intensive tasks",
 "Only network routing",
 "Only audio processing","B"),

("Programming Translators","Differences Among All Three",
 "WebAssembly (Wasm) is a binary instruction format that allows code to run in browsers at:",
 "Very slow speed",
 "Near-native speed, compiled from languages like C, C++, or Rust",
 "No speed at all",
 "Only with JavaScript","B"),

# ── 86 MORE QUESTIONS to reach exactly 1000 total ──

("Cloud Computing","Definition of Cloud Computing",
 "Cloud computing enables horizontal scaling, which means:",
 "Upgrading a single server's hardware",
 "Adding more server instances to handle increased load",
 "Reducing the number of servers",
 "Turning off servers permanently","B"),

("Cloud Computing","Definition of Cloud Computing",
 "Vertical scaling in cloud computing means:",
 "Adding more machines",
 "Increasing the resources (CPU, RAM) of an existing machine",
 "Removing all resources",
 "Only using storage","B"),

("Cloud Computing","Cloud Storage Concept",
 "Block storage in the cloud is ideal for:",
 "Hosting static websites",
 "Databases and applications requiring consistent I/O performance",
 "Only photo sharing",
 "Only email","B"),

("Cloud Computing","Examples of Cloud Usage",
 "Using Google Colab for machine learning experiments is an example of:",
 "On-premise computing only",
 "Cloud-based PaaS/SaaS for computation",
 "No computing at all",
 "Physical notebook usage","B"),

("Cloud Computing","Pay-per-use Model",
 "Spot instances in AWS offer discounted pricing because:",
 "They are permanent",
 "They use spare capacity and can be interrupted by AWS",
 "They have no computing power",
 "They are more expensive than on-demand","B"),

("Cloud Computing","Remote Access Concept",
 "A bastion host in cloud computing is used to:",
 "Store all company data publicly",
 "Provide a secure entry point for SSH access to private cloud resources",
 "Block all remote access",
 "Only host websites","B"),

("Cloud Service Providers","Amazon Web Services (AWS)",
 "AWS IAM (Identity and Access Management) controls:",
 "Physical building access",
 "Who can access which AWS resources and what actions they can perform",
 "Only employee attendance",
 "Only email permissions","B"),

("Cloud Service Providers","Amazon Web Services (AWS)",
 "Amazon SQS (Simple Queue Service) provides:",
 "Physical mail queues",
 "Fully managed message queuing for decoupling microservices",
 "Only printer queues",
 "Only gaming leaderboards","B"),

("Cloud Service Providers","Microsoft Azure",
 "Azure DevOps provides:",
 "Only design tools",
 "CI/CD pipelines, version control, agile planning, and testing tools",
 "Only hardware specifications",
 "Only accounting software","B"),

("Cloud Service Providers","Microsoft Azure",
 "Azure Active Directory (Azure AD) is used for:",
 "Only file storage",
 "Identity management and single sign-on for cloud applications",
 "Only video streaming",
 "Only hardware diagnostics","B"),

("Cloud Service Providers","Difference: AWS vs Azure",
 "IBM Cloud differentiates itself with strong offerings in:",
 "Only consumer products",
 "Enterprise AI (Watson), hybrid cloud, and mainframe integration",
 "Only gaming",
 "Only social media","B"),

("Cloud Service Models","SaaS - Definition",
 "Multi-tenancy in SaaS means that:",
 "Each customer has their own server",
 "Multiple customers share the same application instance with isolated data",
 "Only one customer exists",
 "No data is shared or stored","B"),

("Cloud Service Models","PaaS - Definition",
 "PaaS provides built-in tools for:",
 "Only hardware setup",
 "Application development, testing, deployment, and scaling",
 "Only physical security",
 "Only network cabling","B"),

("Cloud Service Models","IaaS - Definition",
 "Auto-scaling in IaaS automatically adjusts:",
 "Employee numbers",
 "The number of virtual machines based on current demand",
 "Only the font size",
 "Only the screen brightness","B"),

("Cloud Deployment Models","Private Cloud",
 "OpenStack is an open-source platform for building:",
 "Social media applications",
 "Private and public cloud infrastructure",
 "Only mobile games",
 "Only email clients","B"),

("Cloud Deployment Models","Use-case Based Differences",
 "A startup with unpredictable traffic typically chooses public cloud because of:",
 "Higher long-term costs always",
 "Elastic scaling and no upfront capital expenditure",
 "No available options",
 "Regulatory requirements","B"),

("Virtualization & Architecture","Virtualization Definition",
 "Network Function Virtualization (NFV) replaces physical network appliances with:",
 "More physical appliances",
 "Software-based virtual network functions running on standard hardware",
 "No networking at all",
 "Only wireless signals","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "Container runtime (e.g., containerd) differs from hypervisors by not needing:",
 "A host operating system",
 "A separate guest operating system for each workload",
 "Any software",
 "Any hardware","B"),

("Virtualization & Architecture","Role of Hypervisor in IaaS",
 "Multi-tenancy in IaaS relies on hypervisors to ensure:",
 "All customers share data freely",
 "Strong isolation between different customers' virtual machines",
 "No security at all",
 "Only one customer per datacenter","B"),

("Utility & Grid Computing","Grid Computing Definition",
 "Volunteer computing platforms like BOINC enable:",
 "Only professional researchers to contribute",
 "Anyone with a computer to donate idle processing power to scientific projects",
 "Only government agencies to participate",
 "Only companies to contribute","B"),

("Utility & Grid Computing","Pay-per-use Concept",
 "Savings plans in cloud computing offer flexibility by:",
 "Requiring no commitment",
 "Applying discounts to any compute usage matching a committed spend level",
 "Only applying to storage",
 "Increasing costs for all services","B"),

("Utility & Grid Computing","Difference: Grid vs Cloud",
 "Service Level Agreements (SLAs) are more common in cloud computing than grid computing because:",
 "Grid computing has strict SLAs",
 "Cloud providers are commercial entities with contractual obligations",
 "Cloud has no standards",
 "Grid computing doesn't exist anymore","B"),

("SOA & Managed Services","Service-Oriented Architecture (SOA)",
 "RESTful APIs in modern SOA use HTTP methods like GET, POST, PUT, DELETE to:",
 "Only browse websites",
 "Perform CRUD operations on resources",
 "Only send emails",
 "Only print documents","B"),

("SOA & Managed Services","Client-Server Model",
 "Load balancing distributes incoming client requests across multiple servers to:",
 "Slow down responses",
 "Prevent any single server from being overwhelmed",
 "Increase latency",
 "Delete all requests","B"),

("Client & GUI","Client Definition",
 "A Progressive Web App (PWA) is a client application that:",
 "Only works offline",
 "Runs in a browser but can be installed and work offline like a native app",
 "Only works on servers",
 "Requires no internet ever","B"),

("Client & GUI","GUI Definition",
 "The WIMP paradigm in GUI stands for:",
 "Wireless Internet for Mobile Phones",
 "Windows, Icons, Menus, and Pointer",
 "Web Integrated Messaging Platform",
 "Wireless Input Management Protocol","B"),

("Client & GUI","Application Layer Role",
 "SSH (Secure Shell) at the application layer enables:",
 "Unencrypted file transfer only",
 "Secure remote command-line access to servers",
 "Only web browsing",
 "Only video calling","B"),

("Client & GUI","Client-Server Interaction",
 "Server-Sent Events (SSE) allow a server to:",
 "Only receive data from clients",
 "Push real-time updates to clients over a single HTTP connection",
 "Block all client connections",
 "Only serve static files","B"),

("Memory","Primary Memory (RAM)",
 "DDR5 RAM offers higher bandwidth than DDR4 primarily through:",
 "Slower clock speeds",
 "Higher data rates and improved channel architecture",
 "Reducing memory capacity",
 "Using older technology","B"),

("Memory","Secondary Memory",
 "A hybrid drive (SSHD) combines:",
 "Only SSD technology",
 "A traditional HDD with a small SSD cache for faster access",
 "Only magnetic tape",
 "Only floppy disk technology","B"),

("Memory","Magnetic Tape",
 "Iron oxide and chromium dioxide are common materials used in:",
 "SSD manufacturing",
 "Magnetic tape coating for data storage",
 "RAM production",
 "LCD screens","B"),

("Memory","Hard Disk",
 "Defragmentation reorganizes hard disk data so that:",
 "Files become larger",
 "Fragments of files are stored contiguously for faster sequential reads",
 "Files are deleted permanently",
 "The disk spins slower","B"),

("Memory","Floppy Disk",
 "The standard 3.5-inch floppy disk has a rigid plastic case unlike earlier floppies that used:",
 "Metal enclosures",
 "Flexible thin plastic sleeves",
 "Glass cases",
 "Wooden frames","B"),

("Memory","RAM vs Secondary Memory",
 "Virtual memory uses secondary storage to extend available RAM by:",
 "Replacing RAM entirely",
 "Swapping inactive memory pages between RAM and disk",
 "Deleting all RAM contents",
 "Only using flash drives","B"),

("Input/Output Devices","Laser Printer",
 "The transfer roller in a laser printer applies charge to move toner from the drum to:",
 "Back into the cartridge",
 "The paper surface",
 "The fuser unit directly",
 "The air","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "A printer rated at 40 PPM simplex may print at approximately 20 PPM in duplex because:",
 "It runs faster in duplex",
 "Each page must be flipped and printed on the reverse side",
 "Duplex uses more ink",
 "Duplex only prints headers","B"),

("Input/Output Devices","DPI vs PPM",
 "Photo printers prioritize high DPI over high PPM because:",
 "Speed matters more than quality for photos",
 "Image detail and color accuracy are more important than print speed",
 "Photos are always small",
 "Photos don't need dots","B"),

("Keyboard & Hardware","ESC Key",
 "In Linux terminal, pressing ESC then a letter can trigger:",
 "Shutdown",
 "Meta key commands in programs like Emacs",
 "File deletion",
 "Printer activation","B"),

("Keyboard & Hardware","Enter Key",
 "In terminal/command line interfaces, Enter submits the typed command for:",
 "Deletion","Execution by the shell","Printing","Saving to disk only","B"),

("Keyboard & Hardware","Delete Key",
 "Ctrl + Delete in most text editors deletes:",
 "The entire document",
 "The word to the right of the cursor",
 "The entire line",
 "Nothing at all","B"),

("Keyboard & Hardware","Insert Key",
 "Modern laptops often omit the Insert key because:",
 "It was never useful",
 "Overtype mode is rarely used and the key saves keyboard space",
 "It was too expensive",
 "It caused hardware failures","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "Photovoltaic solar cells convert sunlight to electricity using:",
 "Only metals",
 "Semiconductor materials like silicon",
 "Only plastics",
 "Only wood","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "Moore's Law observes that transistor density on chips roughly doubles every:",
 "One month","About two years","Ten years","One hundred years","B"),

("Computer Hardware Basics","Chip Manufacturing Concept",
 "ASML is a key company in chip manufacturing because it produces:",
 "Only software",
 "Advanced EUV lithography machines essential for cutting-edge chips",
 "Only packaging materials",
 "Only cooling systems","B"),

("Types of Computers","Analog Computer",
 "Theremin, an electronic musical instrument, uses analog computing principles to:",
 "Display digital numbers",
 "Generate sound based on the player's hand position in electromagnetic fields",
 "Only record digital audio",
 "Only display text","B"),

("Types of Computers","Digital Computer",
 "ENIAC, completed in 1945, is considered one of the first general-purpose:",
 "Analog computers","Electronic digital computers","Quantum computers","No computer at all","B"),

("Types of Computers","Hybrid Computer Use-cases",
 "Modern robots use hybrid computing: analog sensors feed data to digital processors for:",
 "No purpose",
 "Real-time decision making and precise motor control",
 "Only visual display",
 "Only sound production","B"),

("Storage & Processing","Sequential Access Devices",
 "A singly linked list in programming is a sequential access data structure because:",
 "Any element can be accessed directly",
 "You must traverse from the head node through each subsequent node",
 "It has no elements",
 "It uses random access memory only","B"),

("Storage & Processing","Magnetic Tape Usage",
 "Data migration from old tape formats to new ones is necessary because:",
 "Old tapes never degrade",
 "Tape drives for older formats may become unavailable and tapes degrade over time",
 "New tapes don't store data",
 "Migration is never required","B"),

("Programming Translators","Assembler",
 "ARM assembly language is used in:",
 "Only old mainframes",
 "Mobile devices, embedded systems, and modern Macs with ARM-based chips",
 "Only desktop printers",
 "Only calculators","B"),

("Programming Translators","Compiler",
 "Cross-compilation is the process of compiling code on one platform to run on:",
 "The same platform only",
 "A different target platform (e.g., compiling on x86 for ARM)",
 "No platform at all",
 "Only virtual platforms","B"),

("Programming Translators","Interpreter",
 "REPL (Read-Eval-Print Loop) is an interactive environment provided by interpreters that:",
 "Only reads files",
 "Reads input, evaluates it, prints the result, and loops for more input",
 "Only prints documents",
 "Only loops indefinitely without output","B"),

("Programming Translators","Differences Among All Three",
 "Garbage collection is a memory management feature common in interpreted and some compiled languages that:",
 "Collects physical garbage",
 "Automatically frees memory that is no longer in use",
 "Increases memory leaks",
 "Only works in assembly language","B"),

("Cloud Computing","Advantages of Cloud Computing",
 "Disaster recovery in the cloud is faster than traditional methods because:",
 "Cloud has no backup systems",
 "Data is replicated across multiple geographic regions automatically",
 "Recovery requires physical tape transport only",
 "Disasters never affect cloud systems","B"),

("Cloud Computing","Examples of Cloud Usage",
 "Training a deep learning model on Google Cloud TPUs is an example of:",
 "Cloud-based high-performance computing",
 "Local laptop computing",
 "Manual calculation",
 "Paper-based research","A"),

("Cloud Service Models","SaaS Examples",
 "HubSpot CRM accessed via a web browser is classified as:",
 "IaaS","PaaS","SaaS","FaaS","C"),

("Cloud Service Models","PaaS Examples",
 "Firebase by Google provides backend services and is an example of:",
 "IaaS only","PaaS/BaaS","SaaS only","Hardware","B"),

("Virtualization & Architecture","Single Physical Resource Sharing",
 "CPU pinning assigns specific physical CPU cores to a VM to ensure:",
 "Random performance",
 "Consistent performance by avoiding shared CPU contention",
 "No processing at all",
 "Only single-core usage","B"),

("Virtualization & Architecture","Virtual Machine Isolation",
 "A hypervisor crash could potentially affect all VMs on that host, which is why cloud providers use:",
 "Only one VM per datacenter",
 "Redundancy across multiple physical hosts and availability zones",
 "No backup systems",
 "Only one datacenter globally","B"),

("Utility & Grid Computing","Utility Computing Definition",
 "Serverless computing exemplifies utility computing's vision because users pay:",
 "A flat monthly fee regardless of usage",
 "Only for the exact compute time consumed per function invocation",
 "Nothing at all",
 "For the entire server 24/7","B"),

("Utility & Grid Computing","Heterogeneous Resources",
 "Grid computing middleware translates job requirements so that tasks run correctly on:",
 "Only identical machines",
 "Different operating systems, architectures, and hardware configurations",
 "Only mobile phones",
 "Only one specific computer","B"),

("SOA & Managed Services","Managed IT Services",
 "Managed Detection and Response (MDR) services provide:",
 "Only hardware warranties",
 "24/7 threat monitoring, detection, and response by security experts",
 "Only office supplies",
 "Only parking management","B"),

("Client & GUI","Application Layer Role",
 "SNMP (Simple Network Management Protocol) at the application layer is used for:",
 "Only sending emails",
 "Monitoring and managing network devices like routers and switches",
 "Only web browsing",
 "Only gaming","B"),

("Memory","Hard Disk",
 "S.M.A.R.T. technology in hard disks provides:",
 "Only a brand name",
 "Self-Monitoring, Analysis, and Reporting to predict disk failures",
 "Only encryption",
 "Only formatting tools","B"),

("Memory","Floppy Disk",
 "The term 'floppy' originated because early 8-inch disks:",
 "Were very rigid",
 "Were housed in flexible plastic sleeves and could physically bend",
 "Were made of metal",
 "Could float in water","B"),

("Input/Output Devices","Laser Printer",
 "Color laser printers use four toner cartridges: Cyan, Magenta, Yellow, and:",
 "Red","Black (CMYK color model)","Green","White","B"),

("Keyboard & Hardware","ESC Key",
 "On some keyboards, the ESC key has a physical indentation or gap to help users find it:",
 "By color only","By touch without looking (tactile identification)","By sound","By weight","B"),

("Types of Computers","Analog Computer",
 "An aneroid barometer is an analog device that measures atmospheric pressure using:",
 "Digital sensors",
 "A flexible metal capsule that contracts and expands with pressure changes",
 "Laser beams",
 "Radio waves","B"),

("Types of Computers","Hybrid Computer",
 "An electrocardiogram (ECG) machine is hybrid because it captures analog heart signals and:",
 "Only stores them on paper",
 "Converts them digitally for display, analysis, and storage",
 "Only transmits them by radio",
 "Only plays them as sound","B"),

("Storage & Processing","Sequential Access Devices",
 "Audio cassette tapes used for music are sequential access because you must:",
 "Press one button to jump anywhere",
 "Fast-forward or rewind through the tape to find a specific song",
 "Type a track number to skip",
 "Click on a song from a playlist","B"),

("Programming Translators","Assembler",
 "Assembly language programs are specific to a processor architecture, meaning x86 assembly:",
 "Runs on all processors",
 "Won't run on ARM processors without rewriting",
 "Is identical to ARM assembly",
 "Works on printers too","B"),

("Programming Translators","Compiler",
 "Profile-guided optimization (PGO) uses runtime profiling data to help the compiler:",
 "Slow down the code",
 "Generate more optimized code based on actual usage patterns",
 "Delete the source code",
 "Only format the code","B"),

("Programming Translators","Interpreter",
 "Monkey-patching in interpreted languages allows modification of classes and methods:",
 "Only before writing any code",
 "At runtime without changing the original source code",
 "Only by the compiler",
 "Never at any time","B"),

# ── FINAL 13 Questions ──

("Cloud Computing","Cloud Storage Concept",
 "Data deduplication in cloud storage reduces cost by:",
 "Duplicating all data",
 "Eliminating redundant copies of data to save storage space",
 "Deleting all user data",
 "Only compressing images","B"),

("Cloud Service Providers","Amazon Web Services (AWS)",
 "AWS Regions consist of multiple Availability Zones to ensure:",
 "Data is stored in one place only",
 "High availability and fault tolerance",
 "Slower network speeds",
 "No redundancy at all","B"),

("Cloud Deployment Models","Public Cloud",
 "A startup choosing public cloud avoids:",
 "All technology entirely",
 "Large upfront capital expenditure on hardware",
 "Any form of computing",
 "All software usage","B"),

("Virtualization & Architecture","Hypervisor Definition",
 "QEMU is an open-source machine emulator that can also work with KVM as a:",
 "Web browser",
 "Hypervisor accelerator to run VMs at near-native speed",
 "Word processor",
 "Music player","B"),

("Memory","Primary Memory (RAM)",
 "Registered (buffered) RAM uses a buffer between the memory module and the memory controller to:",
 "Slow down operations",
 "Improve stability in systems with large amounts of RAM",
 "Reduce total capacity",
 "Only for gaming use","B"),

("Memory","Secondary Memory",
 "Wear leveling in SSDs distributes write operations evenly to:",
 "Increase write speed only",
 "Extend the lifespan of the drive by preventing any one cell from wearing out prematurely",
 "Reduce storage capacity",
 "Only benefit HDD drives","B"),

("Input/Output Devices","Printer Speed (PPM)",
 "First Page Out Time (FPOT) measures how quickly a laser printer produces:",
 "The last page of a long job",
 "The very first printed page after receiving a print command",
 "Only blank pages",
 "Only test pages","B"),

("Computer Hardware Basics","Semiconductor Definition",
 "LEDs (Light Emitting Diodes) are semiconductor devices that emit light when:",
 "No current flows",
 "Electric current passes through them in the forward direction",
 "They are submerged in water",
 "They are exposed to extreme cold only","B"),

("Types of Computers","Digital Computer",
 "A workstation is a high-performance digital computer designed for:",
 "Basic web browsing only",
 "Technical or scientific applications like CAD, 3D rendering, and data analysis",
 "Only text editing",
 "Only video playback","B"),

("Storage & Processing","Sequential Access Devices",
 "VHS video tapes are sequential access media because to watch a specific scene you must:",
 "Click a scene menu",
 "Fast-forward or rewind through the tape linearly",
 "Type a timestamp",
 "Select it from a digital menu","B"),

("Programming Translators","Differences Among All Three",
 "Source maps allow debugging of compiled or transpiled code by mapping back to:",
 "Machine code",
 "The original source code for readable debugging",
 "Binary format only",
 "Object code only","B"),

("Cloud Computing","Advantages of Cloud Computing",
 "Geographic redundancy in cloud computing means data is stored in:",
 "Only one data center",
 "Multiple data centers across different geographic locations for disaster protection",
 "No location at all",
 "Only the user's local machine","B"),

("Utility & Grid Computing","Geographically Dispersed Systems",
 "Latency in geographically dispersed grid systems is managed by:",
 "Ignoring it completely",
 "Strategic task placement and data locality optimization",
 "Only using faster light",
 "Removing all network connections","B"),
]
